import { FormEvent, useEffect, useState } from "react";

type Details={client_name:string;client_id:string;scopes:string[];identity_kind:"staff"|"portal"|null;patient_context_required:boolean;expires_at:string};
type Context={identity_kind:"staff"|"portal";patients:{uuid:string;name:string}[];fixed_patient:boolean};

export function SmartAuthorizeApp({baseUrl,navigate=(url:string)=>window.location.assign(url)}:{baseUrl:string;navigate?:(url:string)=>void}){
  const requestToken=new URLSearchParams(window.location.search).get("request")??"";const [details,setDetails]=useState<Details|null>(null);const [token,setToken]=useState("");const [mode,setMode]=useState<"staff"|"portal">("staff");const [challenge,setChallenge]=useState("");const [context,setContext]=useState<Context|null>(null);const [patientUuid,setPatientUuid]=useState("");const [error,setError]=useState("");
  async function json(response:Response){const body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.detail??body?.error_description??"SMART authorization failed");return body;}
  useEffect(()=>{if(!requestToken){setError("Authorization request is missing");return;}void fetch(`${baseUrl}/oauth2/default/authorize/requests/${requestToken}`,{credentials:"include"}).then(json).then((value:Details)=>{setDetails(value);if(value.identity_kind)setMode(value.identity_kind);}).catch(reason=>setError(reason.message));},[requestToken]);
  useEffect(()=>{if(!token)return;void fetch(`${baseUrl}/oauth2/default/authorize/requests/${requestToken}/context`,{headers:{Authorization:`Bearer ${token}`},credentials:"include"}).then(json).then((value:Context)=>{setContext(value);setPatientUuid(value.patients[0]?.uuid??"");}).catch(reason=>{setToken("");setError(reason.message);});},[token,requestToken]);
  async function login(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");const data=new FormData(event.currentTarget);const path=mode==="staff"?"/api/v1/auth/token":"/api/v1/portal/auth/token";try{const result=await json(await fetch(`${baseUrl}${path}`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(mode==="staff"?{email:data.get("username"),password:data.get("password")}:{username:data.get("username"),password:data.get("password")})}));if(result.force_password_reset)throw new Error("Replace the temporary portal password before authorizing an application");if(result.mfa_required)setChallenge(result.challenge_token);else setToken(result.access_token);}catch(reason){setError(reason instanceof Error?reason.message:"Sign-in failed");}}
  async function verify(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const path=mode==="staff"?"/api/v1/auth/mfa/challenge":"/api/v1/portal/auth/mfa/challenge";try{const result=await json(await fetch(`${baseUrl}${path}`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({challenge_token:challenge,code:data.get("code")})}));setChallenge("");setToken(result.access_token);}catch(reason){setError(reason instanceof Error?reason.message:"MFA verification failed");}}
  async function decide(approve:boolean){if(!token)return;setError("");try{const result=await json(await fetch(`${baseUrl}/oauth2/default/authorize/requests/${requestToken}/${approve?"approve":"deny"}`,{method:"POST",credentials:"include",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:approve?JSON.stringify({patient_uuid:patientUuid||null}):undefined}));navigate(result.redirect_to);}catch(reason){setError(reason instanceof Error?reason.message:"Authorization failed");}}
  if(!details)return <main className="login"><form><p className="eyebrow">SMART ON FHIR</p><h1>Application authorization</h1><p>{error||"Loading secure authorization request…"}</p></form></main>;
  if(challenge)return <main className="login"><form onSubmit={verify}><p className="eyebrow">SMART ON FHIR</p><h1>Security code</h1><label>Authenticator or recovery code<input name="code" autoComplete="one-time-code" required autoFocus/></label>{error&&<p className="error">{error}</p>}<button>Verify identity</button></form></main>;
  if(!token)return <main className="login"><form onSubmit={login}><p className="eyebrow">SMART ON FHIR</p><h1>Authorize {details.client_name}</h1><p>Sign in to review the requested health-data access.</p>{!details.identity_kind&&<label>Identity<select aria-label="Identity type" value={mode} onChange={event=>setMode(event.target.value as "staff"|"portal")}><option value="staff">Clinical staff</option><option value="portal">Patient portal</option></select></label>}<label>{mode==="staff"?"Email":"Portal username"}<input name="username" type={mode==="staff"?"email":"text"} required/></label><label>Password<input name="password" type="password" required/></label>{error&&<p className="error">{error}</p>}<button>Continue securely</button></form></main>;
  return <main className="login"><form><p className="eyebrow">SMART ON FHIR</p><h1>Allow {details.client_name}?</h1><p>The application requests:</p><ul>{details.scopes.map(scope=><li key={scope}><code>{scope}</code></li>)}</ul>{details.patient_context_required&&<label>Patient context<select aria-label="Patient context" value={patientUuid} onChange={event=>setPatientUuid(event.target.value)} disabled={context?.fixed_patient}>{context?.patients.map(patient=><option key={patient.uuid} value={patient.uuid}>{patient.name}</option>)}</select></label>}{details.patient_context_required&&!context?.patients.length&&<p className="error">No authorized patient context is available.</p>}{error&&<p className="error">{error}</p>}<button type="button" disabled={details.patient_context_required&&!patientUuid} onClick={()=>void decide(true)}>Allow access</button><button className="secondary" type="button" onClick={()=>void decide(false)}>Deny</button></form></main>;
}
