import { FormEvent, useEffect, useState } from "react";
import type { ApiRequest } from "../../api/client";

type Facility={uuid:string;name:string;city?:string;state?:string;npi?:string;active:boolean};
type Warehouse={uuid:string;code:string;name:string;facility_uuid?:string;active:boolean};
type Practitioner={uuid:string;first_name:string;last_name:string;specialty?:string;npi?:string;primary_facility_uuid?:string;calendar_enabled:boolean;active:boolean};
type EducationResource={uuid:string;name:string;url_template:string;sequence:number;active:boolean};
type SmartClient={uuid:string;client_id:string;name:string;client_kind:"backend"|"interactive";redirect_uris:string[];launch_uri?:string;launch_types:string[];allowed_scopes:string[];active:boolean;created_at:string};
type ManagedUser={uuid:string;username?:string;email:string;role:string;active:boolean;permissions:string[]};
type ManagedSetting={uuid:string;key:string;category:string;value_type:string;value:unknown;description:string;version:number};
type Locale={uuid:string;code:string;name:string;rtl:boolean;active:boolean};
type ContentTemplate={uuid:string;key:string;locale_code:string;version:number;name:string;category:string;subject?:string;content:string;content_type:string;allowed_variables:string[];active:boolean};

export function AdministrationWorkspace({api}:{api:ApiRequest}){
  const [facilities,setFacilities]=useState<Facility[]>([]);const [warehouses,setWarehouses]=useState<Warehouse[]>([]);const [practitioners,setPractitioners]=useState<Practitioner[]>([]);const [education,setEducation]=useState<EducationResource[]>([]);const [smartClients,setSmartClients]=useState<SmartClient[]>([]);const [users,setUsers]=useState<ManagedUser[]>([]);const [settings,setSettings]=useState<ManagedSetting[]>([]);const [locales,setLocales]=useState<Locale[]>([]);const [templates,setTemplates]=useState<ContentTemplate[]>([]);const [error,setError]=useState("");
  async function load(){try{const [f,w,p,e,s,u,g,l,t]=await Promise.all([api<Facility[]>("/api/v1/admin/facilities"),api<Warehouse[]>("/api/v1/admin/warehouses"),api<Practitioner[]>("/api/v1/admin/practitioners"),api<EducationResource[]>("/api/v1/admin/patient-education/resources"),api<SmartClient[]>("/api/v1/admin/smart-clients"),api<ManagedUser[]>("/api/v1/admin/users"),api<ManagedSetting[]>("/api/v1/admin/settings"),api<Locale[]>("/api/v1/admin/locales"),api<ContentTemplate[]>("/api/v1/admin/templates")]);setFacilities(f);setWarehouses(w);setPractitioners(p);setEducation(e);setSmartClients(s);setUsers(u);setSettings(g);setLocales(l);setTemplates(t);setError("");}catch(reason){setError(reason instanceof Error?reason.message:"Could not load administration data");}}
  useEffect(()=>{void load();},[]);
  async function submit(event:FormEvent<HTMLFormElement>,path:string,body:(data:FormData)=>unknown){event.preventDefault();const form=event.currentTarget,data=new FormData(form);try{await api(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body(data))});form.reset();await load();}catch(reason){setError(reason instanceof Error?reason.message:"Could not save administration data");}}
  const createFacility=(event:FormEvent<HTMLFormElement>)=>submit(event,"/api/v1/admin/facilities",data=>({name:data.get("name"),city:data.get("city")||null,state:data.get("state")||null,npi:data.get("npi")||null}));
  const createWarehouse=(event:FormEvent<HTMLFormElement>)=>submit(event,"/api/v1/admin/warehouses",data=>({code:data.get("code"),name:data.get("name"),facility_uuid:data.get("facility_uuid")||null}));
  const createPractitioner=(event:FormEvent<HTMLFormElement>)=>submit(event,"/api/v1/admin/practitioners",data=>({first_name:data.get("first_name"),last_name:data.get("last_name"),specialty:data.get("specialty")||null,npi:data.get("npi")||null,primary_facility_uuid:data.get("primary_facility_uuid")||null,calendar_enabled:data.get("calendar_enabled")==="on"}));
  const createEducationResource=(event:FormEvent<HTMLFormElement>)=>submit(event,"/api/v1/admin/patient-education/resources",data=>({name:data.get("name"),url_template:data.get("url_template"),sequence:Number(data.get("sequence")||0),active:true}));
  const createSmartClient=(event:FormEvent<HTMLFormElement>)=>submit(event,"/api/v1/admin/smart-clients",data=>{const jwks=String(data.get("jwks")||"").trim();return{name:data.get("name"),client_id:data.get("client_id")||null,client_kind:data.get("client_kind"),jwks:jwks?JSON.parse(jwks):null,redirect_uris:String(data.get("redirect_uris")||"").split(/\s+/).filter(Boolean),launch_uri:data.get("launch_uri")||null,launch_types:String(data.get("launch_types")||"").split(/[,\s]+/).filter(Boolean),allowed_scopes:String(data.get("allowed_scopes")||"").split(/\s+/).filter(Boolean)}});
  const inviteUser=(event:FormEvent<HTMLFormElement>)=>submit(event,"/api/v1/admin/users/invitations",data=>({email:data.get("email"),username:data.get("username")||null,role:data.get("role"),permissions:String(data.get("permissions")||"").split(/[,\s]+/).filter(Boolean)}));
  const createLocale=(event:FormEvent<HTMLFormElement>)=>submit(event,"/api/v1/admin/locales",data=>({code:data.get("code"),name:data.get("name"),rtl:data.get("rtl")==="on",active:true}));
  const createTemplate=(event:FormEvent<HTMLFormElement>)=>submit(event,"/api/v1/admin/templates",data=>({key:data.get("key"),locale_code:data.get("locale_code"),name:data.get("name"),category:data.get("category"),subject:data.get("subject")||null,content:data.get("content"),content_type:data.get("content_type"),allowed_variables:String(data.get("allowed_variables")||"").split(/[,\s]+/).filter(Boolean)}));
  async function saveSetting(item:ManagedSetting,value:string){let parsed:unknown=value;if(item.value_type==="integer")parsed=Number(value);try{await api(`/api/v1/admin/settings/${item.key}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({value:parsed})});await load();}catch(reason){setError(reason instanceof Error?reason.message:"Could not update setting");}}
  async function toggleUser(item:ManagedUser){try{await api(`/api/v1/admin/users/${item.uuid}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({active:!item.active})});await load();}catch(reason){setError(reason instanceof Error?reason.message:"Could not update user");}}
  async function editUserAccess(item:ManagedUser){const role=window.prompt("Role: admin, billing, clinician, or receptionist",item.role);if(!role)return;const raw=window.prompt("Permission grants, separated by spaces",item.permissions.join(" "));if(raw===null)return;try{await api(`/api/v1/admin/users/${item.uuid}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({role,permissions:raw.split(/[,\s]+/).filter(Boolean)})});await load();}catch(reason){setError(reason instanceof Error?reason.message:"Could not update user access");}}
  async function editTranslation(locale:Locale){const key=window.prompt("Translation key");if(!key)return;const value=window.prompt(`Value for ${key}`);if(value===null)return;try{await api(`/api/v1/admin/locales/${locale.code}/translations/${encodeURIComponent(key)}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({value})});}catch(reason){setError(reason instanceof Error?reason.message:"Could not update translation");}}
  async function previewTemplate(item:ContentTemplate){const raw=window.prompt("Preview variables as JSON",JSON.stringify(Object.fromEntries(item.allowed_variables.map(key=>[key,key]))));if(raw===null)return;try{const result=await api<{subject?:string;content:string}>(`/api/v1/admin/templates/${item.uuid}/preview`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({variables:JSON.parse(raw)})});window.alert([result.subject,result.content].filter(Boolean).join("\n\n"));}catch(reason){setError(reason instanceof Error?reason.message:"Could not preview template");}}
  async function versionTemplate(item:ContentTemplate){const content=window.prompt("Content for the new immutable version",item.content);if(content===null||content===item.content)return;try{await api(`/api/v1/admin/templates/${item.uuid}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({key:item.key,locale_code:item.locale_code,name:item.name,category:item.category,subject:item.subject??null,content,content_type:item.content_type,allowed_variables:item.allowed_variables})});await load();}catch(reason){setError(reason instanceof Error?reason.message:"Could not version template");}}
  async function revokeSmartClient(uuid:string){try{await api(`/api/v1/admin/smart-clients/${uuid}`,{method:"DELETE"});await load();}catch(reason){setError(reason instanceof Error?reason.message:"Could not revoke SMART client");}}
  return <section className="admin-workspace">{error&&<p className="error">{error}</p>}<div className="admin-columns">
    <section className="card admin-panel"><h2>Facilities</h2><form className="quick-add" onSubmit={createFacility}><input name="name" placeholder="Facility name" required/><input name="city" placeholder="City"/><input name="state" placeholder="State"/><input name="npi" placeholder="Facility NPI"/><button>Add facility</button></form>{facilities.map(item=><article key={item.uuid}><strong>{item.name}</strong><small>{[item.city,item.state,item.npi].filter(Boolean).join(" · ")||"No additional details"}</small></article>)}</section>
    <section className="card admin-panel"><h2>Warehouses</h2><form className="quick-add" onSubmit={createWarehouse}><input name="code" placeholder="Warehouse code" required/><input name="name" placeholder="Warehouse name" required/><select name="facility_uuid"><option value="">No facility</option>{facilities.map(item=><option key={item.uuid} value={item.uuid}>{item.name}</option>)}</select><button>Add warehouse</button></form>{warehouses.map(item=><article key={item.uuid}><strong>{item.name}</strong><small>{item.code} · {facilities.find(f=>f.uuid===item.facility_uuid)?.name??"Unassigned"}</small></article>)}</section>
    <section className="card admin-panel"><h2>Practitioners</h2><form className="quick-add" onSubmit={createPractitioner}><input name="first_name" placeholder="First name" required/><input name="last_name" placeholder="Last name" required/><input name="specialty" placeholder="Specialty"/><input name="npi" placeholder="NPI"/><select name="primary_facility_uuid"><option value="">No primary facility</option>{facilities.map(item=><option key={item.uuid} value={item.uuid}>{item.name}</option>)}</select><label><input name="calendar_enabled" type="checkbox"/> Show in calendar</label><button>Add practitioner</button></form>{practitioners.map(item=><article key={item.uuid}><strong>{item.last_name}, {item.first_name}</strong><small>{item.specialty??"No specialty"}{item.calendar_enabled?" · Calendar":""}</small></article>)}</section>
    <section className="card admin-panel"><h2>Patient education resources</h2><form className="quick-add" onSubmit={createEducationResource}><input name="name" placeholder="Resource name" required/><input name="url_template" type="url" placeholder="https://example.org/search?q=[%]" required/><input name="sequence" type="number" min="0" defaultValue="0"/><button>Add resource</button></form>{education.map(item=><article key={item.uuid}><strong>{item.name}</strong><small>{item.active?"Active":"Inactive"} · order {item.sequence}</small></article>)}</section>
    <section className="card admin-panel"><h2>SMART applications</h2><p>Backend clients register public JWKs; interactive public clients register exact redirect and launch URIs.</p><form className="quick-add" onSubmit={createSmartClient}><input name="name" placeholder="Client name" required/><input name="client_id" placeholder="Client ID (optional)"/><select name="client_kind" aria-label="SMART client type"><option value="backend">Backend service</option><option value="interactive">Interactive public app</option></select><textarea name="jwks" aria-label="Public JWKS" placeholder={'{"keys":[...]} (backend only)'}/><textarea name="redirect_uris" aria-label="Redirect URIs" placeholder="https://app.example.org/callback"/><input name="launch_uri" aria-label="Launch URI" placeholder="https://app.example.org/launch"/><input name="launch_types" aria-label="Launch types" placeholder="standalone ehr patient"/><input name="allowed_scopes" aria-label="Allowed SMART scopes" placeholder="patient/Patient.rs openid fhirUser" required/><button>Register SMART application</button></form>{smartClients.map(item=><article key={item.uuid}><strong>{item.name}</strong><small>{item.client_id} · {item.client_kind} · {item.launch_types.join(" ")||"service"} · {item.allowed_scopes.join(" ")} · {item.active?"Active":"Revoked"}</small>{item.active&&<button onClick={()=>void revokeSmartClient(item.uuid)}>Revoke</button>}</article>)}</section>
    <section className="card admin-panel"><h2>User administration</h2><p>Invite staff without transmitting temporary passwords and manage application access.</p><form className="quick-add" onSubmit={inviteUser}><input name="email" type="email" placeholder="Staff email" required/><input name="username" placeholder="Username (optional)"/><select name="role"><option value="clinician">Clinician</option><option value="receptionist">Receptionist</option><option value="billing">Billing</option><option value="admin">Administrator</option></select><input name="permissions" placeholder="Permission grants, separated by spaces"/><button>Send invitation</button></form>{users.map(item=><article key={item.uuid}><strong>{item.email}</strong><small>{item.role} · {item.permissions.join(" ")||"No grants"} · {item.active?"Active":"Disabled"}</small><button onClick={()=>void editUserAccess(item)}>Edit access</button><button onClick={()=>void toggleUser(item)}>{item.active?"Disable":"Activate"}</button></article>)}</section>
    <section className="card admin-panel"><h2>Safe configuration</h2><p>Only reviewed, non-secret runtime settings are editable here.</p>{settings.map(item=><form className="quick-add" key={item.uuid} onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget);void saveSetting(item,String(data.get("value")??""));}}><label>{item.key}<input name="value" defaultValue={String(item.value)}/><small>{item.description} · version {item.version}</small></label><button>Save</button></form>)}</section>
    <section className="card admin-panel"><h2>Locales</h2><form className="quick-add" onSubmit={createLocale}><input name="code" placeholder="Locale code" required/><input name="name" placeholder="Locale name" required/><label><input name="rtl" type="checkbox"/> Right-to-left</label><button>Add locale</button></form>{locales.map(item=><article key={item.uuid}><strong>{item.name}</strong><small>{item.code} · {item.rtl?"RTL":"LTR"} · {item.active?"Active":"Inactive"}</small><button onClick={()=>void editTranslation(item)}>Edit translation</button></article>)}</section>
    <section className="card admin-panel"><h2>Versioned templates</h2><form className="quick-add" onSubmit={createTemplate}><input name="key" placeholder="Template key" required/><input name="name" placeholder="Template name" required/><select name="locale_code">{locales.filter(item=>item.active).map(item=><option key={item.uuid} value={item.code}>{item.name}</option>)}</select><select name="category"><option value="document">Document</option><option value="clinical">Clinical</option><option value="email">Email</option><option value="sms">SMS</option></select><select name="content_type"><option value="text/plain">Plain text</option><option value="text/html">HTML</option></select><input name="subject" placeholder="Subject (optional)"/><input name="allowed_variables" placeholder="Allowed variables"/><textarea name="content" placeholder="Content with {{variable}} placeholders" required/><button>Create template</button></form>{templates.map(item=><article key={item.uuid}><strong>{item.name}</strong><small>{item.key} · {item.locale_code} · v{item.version} · {item.category}</small><button onClick={()=>void previewTemplate(item)}>Preview</button><button onClick={()=>void versionTemplate(item)}>New version</button></article>)}</section>
  </div></section>;
}
