import { FormEvent, useEffect, useState } from "react";
import type { ApiRequest } from "../../api/client";

type Facility={uuid:string;name:string;city?:string;state?:string;npi?:string;active:boolean};
type Warehouse={uuid:string;code:string;name:string;facility_uuid?:string;active:boolean};
type Practitioner={uuid:string;first_name:string;last_name:string;specialty?:string;npi?:string;primary_facility_uuid?:string;calendar_enabled:boolean;active:boolean};
type EducationResource={uuid:string;name:string;url_template:string;sequence:number;active:boolean};
type SmartClient={uuid:string;client_id:string;name:string;client_kind:"backend"|"interactive";redirect_uris:string[];launch_uri?:string;launch_types:string[];allowed_scopes:string[];active:boolean;created_at:string};

export function AdministrationWorkspace({api}:{api:ApiRequest}){
  const [facilities,setFacilities]=useState<Facility[]>([]);const [warehouses,setWarehouses]=useState<Warehouse[]>([]);const [practitioners,setPractitioners]=useState<Practitioner[]>([]);const [education,setEducation]=useState<EducationResource[]>([]);const [smartClients,setSmartClients]=useState<SmartClient[]>([]);const [error,setError]=useState("");
  async function load(){try{const [f,w,p,e,s]=await Promise.all([api<Facility[]>("/api/v1/admin/facilities"),api<Warehouse[]>("/api/v1/admin/warehouses"),api<Practitioner[]>("/api/v1/admin/practitioners"),api<EducationResource[]>("/api/v1/admin/patient-education/resources"),api<SmartClient[]>("/api/v1/admin/smart-clients")]);setFacilities(f);setWarehouses(w);setPractitioners(p);setEducation(e);setSmartClients(s);setError("");}catch(reason){setError(reason instanceof Error?reason.message:"Could not load administration data");}}
  useEffect(()=>{void load();},[]);
  async function submit(event:FormEvent<HTMLFormElement>,path:string,body:(data:FormData)=>unknown){event.preventDefault();const form=event.currentTarget,data=new FormData(form);try{await api(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body(data))});form.reset();await load();}catch(reason){setError(reason instanceof Error?reason.message:"Could not save administration data");}}
  const createFacility=(event:FormEvent<HTMLFormElement>)=>submit(event,"/api/v1/admin/facilities",data=>({name:data.get("name"),city:data.get("city")||null,state:data.get("state")||null,npi:data.get("npi")||null}));
  const createWarehouse=(event:FormEvent<HTMLFormElement>)=>submit(event,"/api/v1/admin/warehouses",data=>({code:data.get("code"),name:data.get("name"),facility_uuid:data.get("facility_uuid")||null}));
  const createPractitioner=(event:FormEvent<HTMLFormElement>)=>submit(event,"/api/v1/admin/practitioners",data=>({first_name:data.get("first_name"),last_name:data.get("last_name"),specialty:data.get("specialty")||null,npi:data.get("npi")||null,primary_facility_uuid:data.get("primary_facility_uuid")||null,calendar_enabled:data.get("calendar_enabled")==="on"}));
  const createEducationResource=(event:FormEvent<HTMLFormElement>)=>submit(event,"/api/v1/admin/patient-education/resources",data=>({name:data.get("name"),url_template:data.get("url_template"),sequence:Number(data.get("sequence")||0),active:true}));
  const createSmartClient=(event:FormEvent<HTMLFormElement>)=>submit(event,"/api/v1/admin/smart-clients",data=>{const jwks=String(data.get("jwks")||"").trim();return{name:data.get("name"),client_id:data.get("client_id")||null,client_kind:data.get("client_kind"),jwks:jwks?JSON.parse(jwks):null,redirect_uris:String(data.get("redirect_uris")||"").split(/\s+/).filter(Boolean),launch_uri:data.get("launch_uri")||null,launch_types:String(data.get("launch_types")||"").split(/[,\s]+/).filter(Boolean),allowed_scopes:String(data.get("allowed_scopes")||"").split(/\s+/).filter(Boolean)}});
  async function revokeSmartClient(uuid:string){try{await api(`/api/v1/admin/smart-clients/${uuid}`,{method:"DELETE"});await load();}catch(reason){setError(reason instanceof Error?reason.message:"Could not revoke SMART client");}}
  return <section className="admin-workspace">{error&&<p className="error">{error}</p>}<div className="admin-columns">
    <section className="card admin-panel"><h2>Facilities</h2><form className="quick-add" onSubmit={createFacility}><input name="name" placeholder="Facility name" required/><input name="city" placeholder="City"/><input name="state" placeholder="State"/><input name="npi" placeholder="Facility NPI"/><button>Add facility</button></form>{facilities.map(item=><article key={item.uuid}><strong>{item.name}</strong><small>{[item.city,item.state,item.npi].filter(Boolean).join(" · ")||"No additional details"}</small></article>)}</section>
    <section className="card admin-panel"><h2>Warehouses</h2><form className="quick-add" onSubmit={createWarehouse}><input name="code" placeholder="Warehouse code" required/><input name="name" placeholder="Warehouse name" required/><select name="facility_uuid"><option value="">No facility</option>{facilities.map(item=><option key={item.uuid} value={item.uuid}>{item.name}</option>)}</select><button>Add warehouse</button></form>{warehouses.map(item=><article key={item.uuid}><strong>{item.name}</strong><small>{item.code} · {facilities.find(f=>f.uuid===item.facility_uuid)?.name??"Unassigned"}</small></article>)}</section>
    <section className="card admin-panel"><h2>Practitioners</h2><form className="quick-add" onSubmit={createPractitioner}><input name="first_name" placeholder="First name" required/><input name="last_name" placeholder="Last name" required/><input name="specialty" placeholder="Specialty"/><input name="npi" placeholder="NPI"/><select name="primary_facility_uuid"><option value="">No primary facility</option>{facilities.map(item=><option key={item.uuid} value={item.uuid}>{item.name}</option>)}</select><label><input name="calendar_enabled" type="checkbox"/> Show in calendar</label><button>Add practitioner</button></form>{practitioners.map(item=><article key={item.uuid}><strong>{item.last_name}, {item.first_name}</strong><small>{item.specialty??"No specialty"}{item.calendar_enabled?" · Calendar":""}</small></article>)}</section>
    <section className="card admin-panel"><h2>Patient education resources</h2><form className="quick-add" onSubmit={createEducationResource}><input name="name" placeholder="Resource name" required/><input name="url_template" type="url" placeholder="https://example.org/search?q=[%]" required/><input name="sequence" type="number" min="0" defaultValue="0"/><button>Add resource</button></form>{education.map(item=><article key={item.uuid}><strong>{item.name}</strong><small>{item.active?"Active":"Inactive"} · order {item.sequence}</small></article>)}</section>
    <section className="card admin-panel"><h2>SMART applications</h2><p>Backend clients register public JWKs; interactive public clients register exact redirect and launch URIs.</p><form className="quick-add" onSubmit={createSmartClient}><input name="name" placeholder="Client name" required/><input name="client_id" placeholder="Client ID (optional)"/><select name="client_kind" aria-label="SMART client type"><option value="backend">Backend service</option><option value="interactive">Interactive public app</option></select><textarea name="jwks" aria-label="Public JWKS" placeholder={'{"keys":[...]} (backend only)'}/><textarea name="redirect_uris" aria-label="Redirect URIs" placeholder="https://app.example.org/callback"/><input name="launch_uri" aria-label="Launch URI" placeholder="https://app.example.org/launch"/><input name="launch_types" aria-label="Launch types" placeholder="standalone ehr patient"/><input name="allowed_scopes" aria-label="Allowed SMART scopes" placeholder="patient/Patient.rs openid fhirUser" required/><button>Register SMART application</button></form>{smartClients.map(item=><article key={item.uuid}><strong>{item.name}</strong><small>{item.client_id} · {item.client_kind} · {item.launch_types.join(" ")||"service"} · {item.allowed_scopes.join(" ")} · {item.active?"Active":"Revoked"}</small>{item.active&&<button onClick={()=>void revokeSmartClient(item.uuid)}>Revoke</button>}</article>)}</section>
  </div></section>;
}
