import { FormEvent, useEffect, useState } from "react";
import type { ApiRequest } from "../../api/client";

type CarePlan={uuid:string;encounter_uuid:string;recorded_at:string;code?:string;code_text?:string;description:string;external_id?:string;plan_type?:string;note_related_to?:string;ends_at?:string;reason_code?:string;reason_description?:string;reason_recorded_at?:string;reason_ends_at?:string;reason_status?:string;status:string;target_date?:string;engagement_category?:string;active:boolean;created_at:string;updated_at:string};
const editable=(item:CarePlan)=>Object.fromEntries(Object.entries(item).filter(([key])=>!["uuid","encounter_uuid","active","created_at","updated_at"].includes(key)));
const iso=(value:FormDataEntryValue|null)=>value?new Date(String(value)).toISOString():null;

export function CarePlanWorkspace({api,patientUuid,encounterUuid,locked=false}:{api:ApiRequest;patientUuid:string;encounterUuid:string;locked?:boolean}){
  const [plans,setPlans]=useState<CarePlan[]>([]),[error,setError]=useState("");const path=`/api/v1/patients/${patientUuid}/care-plans`;
  async function load(){try{setPlans(await api<CarePlan[]>(path));}catch(reason){setError(reason instanceof Error?reason.message:"No se pudieron cargar los planes");}}
  useEffect(()=>{void load();},[patientUuid]);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");const form=event.currentTarget,data=new FormData(form);const reasonCode=String(data.get("reason_code")??"").trim();try{await api(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({encounter_uuid:encounterUuid,recorded_at:iso(data.get("recorded_at")),code:data.get("code")||null,code_text:data.get("code_text")||null,description:data.get("description"),plan_type:data.get("plan_type")||null,status:data.get("status"),target_date:iso(data.get("target_date")),ends_at:iso(data.get("ends_at")),engagement_category:data.get("engagement_category")||null,reason_code:reasonCode||null,reason_description:data.get("reason_description")||null,reason_status:reasonCode?data.get("reason_status"):null,reason_recorded_at:reasonCode?iso(data.get("reason_recorded_at")):null})});form.reset();await load();}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo crear el plan");}}
  async function setStatus(item:CarePlan,status:string){try{await api(`${path}/${item.uuid}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({...editable(item),status})});await load();}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo actualizar el plan");}}
  async function inactivate(item:CarePlan){const reason=window.prompt("Motivo para inactivar el plan");if(!reason)return;try{await api(`${path}/${item.uuid}?reason=${encodeURIComponent(reason)}`,{method:"DELETE"});await load();}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo inactivar el plan");}}
  return <section className="summary-group care-plan-workspace"><h3>Planes de cuidado<span>{plans.length}</span></h3>{plans.map(item=><article key={item.uuid}><strong>{item.code_text||item.code||item.plan_type||"Plan de cuidado"}</strong><p>{item.description}</p><small>{item.status} · objetivo {item.target_date?new Date(item.target_date).toLocaleDateString():"sin fecha"}</small>{!locked&&<div><select aria-label={`Estado ${item.description}`} value={item.status} onChange={event=>void setStatus(item,event.target.value)}><option value="draft">Borrador</option><option value="active">Activo</option><option value="on-hold">En pausa</option><option value="completed">Completado</option><option value="cancelled">Cancelado</option><option value="entered-in-error">Error</option></select><button type="button" className="text-button" onClick={()=>void inactivate(item)}>Inactivar</button></div>}</article>)}
    {!locked&&<details><summary>Nuevo plan de cuidado</summary><form className="care-plan-form" onSubmit={create}><label>Registrado<input name="recorded_at" type="datetime-local" required/></label><label>Código<input name="code"/></label><label>Descripción del código<input name="code_text"/></label><label>Tipo<input name="plan_type"/></label><label>Estado<select name="status" defaultValue="draft"><option value="draft">Borrador</option><option value="active">Activo</option><option value="on-hold">En pausa</option><option value="completed">Completado</option></select></label><label>Objetivo<input name="target_date" type="datetime-local"/></label><label>Fin previsto<input name="ends_at" type="datetime-local"/></label><label>Participación<input name="engagement_category"/></label><label className="wide">Descripción<textarea name="description" required maxLength={20_000}/></label><label>Código de razón<input name="reason_code"/></label><label>Estado de razón<input name="reason_status"/></label><label>Fecha de razón<input name="reason_recorded_at" type="datetime-local"/></label><label className="wide">Descripción de razón<textarea name="reason_description"/></label><button>Agregar plan</button></form></details>}{error&&<p className="error">{error}</p>}
  </section>;
}
