import { FormEvent, useEffect, useState } from "react";
import type { ApiRequest } from "../../api/client";

type CatalogItem={uuid:string;name:string;specialty?:string};type Catalog={practitioners:CatalogItem[];facilities:CatalogItem[]};
type Member={uuid:string;member_type:string;practitioner_uuid?:string;facility_uuid?:string;contact_name?:string;display_name:string;role:string;provider_since?:string;status:string;note?:string;inactivated_reason?:string};
type Team={uuid:string;name:string;status:string;note?:string;members:Member[]};

export function CareTeamWorkspace({api,patientUuid}:{api:ApiRequest;patientUuid:string}){
  const base=`/api/v1/patients/${patientUuid}/care-teams`;const [teams,setTeams]=useState<Team[]>([]),[catalog,setCatalog]=useState<Catalog>({practitioners:[],facilities:[]}),[error,setError]=useState("");
  async function load(){try{const [items,options]=await Promise.all([api<Team[]>(base),api<Catalog>(`/api/v1/patients/${patientUuid}/care-team-catalog`)]);setTeams(items);setCatalog(options);}catch(reason){setError(reason instanceof Error?reason.message:"No se pudieron cargar los equipos");}}
  useEffect(()=>{void load();},[patientUuid]);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);try{await api(base,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:data.get("name"),status:"proposed",note:data.get("note")||null})});form.reset();await load();}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo crear el equipo");}}
  async function addMember(event:FormEvent<HTMLFormElement>,team:Team){event.preventDefault();const form=event.currentTarget,data=new FormData(form),memberType=String(data.get("member_type"));try{await api(`${base}/${team.uuid}/members`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({member_type:memberType,practitioner_uuid:memberType==="practitioner"?data.get("practitioner_uuid"):null,facility_uuid:memberType!=="contact"?data.get("facility_uuid")||null:null,contact_name:memberType==="contact"?data.get("contact_name"):null,role:data.get("role"),provider_since:data.get("provider_since")||null,status:"active"})});form.reset();await load();}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo agregar el participante");}}
  async function setTeamStatus(team:Team,status:string){try{await api(`${base}/${team.uuid}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:team.name,status,note:team.note??null})});await load();}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo actualizar el equipo");}}
  async function setMemberStatus(team:Team,member:Member,status:string){try{await api(`${base}/${team.uuid}/members/${member.uuid}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({role:member.role,provider_since:member.provider_since??null,status,note:member.note??null})});await load();}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo actualizar el participante");}}
  async function inactivate(team:Team,member?:Member){const reason=window.prompt("Motivo de inactivación");if(!reason)return;const path=member?`${base}/${team.uuid}/members/${member.uuid}`:`${base}/${team.uuid}`;try{await api(`${path}?reason=${encodeURIComponent(reason)}`,{method:"DELETE"});await load();}catch(cause){setError(cause instanceof Error?cause.message:"No se pudo inactivar");}}
  return <section className="summary-group care-team-workspace"><h3>Equipos de atención<span>{teams.length}</span></h3>{teams.map(team=><details key={team.uuid}><summary><strong>{team.name}</strong> · {team.status}</summary>{team.note&&<p>{team.note}</p>}<select aria-label={`Estado de ${team.name}`} value={team.status} onChange={event=>void setTeamStatus(team,event.target.value)}><option value="proposed">Propuesto</option><option value="active">Activo</option><option value="suspended">Suspendido</option></select><button type="button" className="text-button" onClick={()=>void inactivate(team)}>Inactivar equipo</button>{team.members.map(member=><article key={member.uuid}><strong>{member.display_name}</strong><small>{member.role}{member.provider_since?` · desde ${member.provider_since}`:""}</small>{!['inactive','entered-in-error'].includes(member.status)&&<><select aria-label={`Estado de ${member.display_name}`} value={member.status} onChange={event=>void setMemberStatus(team,member,event.target.value)}><option value="proposed">Propuesto</option><option value="active">Activo</option><option value="suspended">Suspendido</option></select><button type="button" className="text-button" onClick={()=>void inactivate(team,member)}>Inactivar participante</button></>}</article>)}<form className="care-team-member-form" onSubmit={event=>addMember(event,team)}><select name="member_type" aria-label="Tipo de participante"><option value="practitioner">Profesional</option><option value="facility">Instalación</option><option value="contact">Contacto externo</option></select><select name="practitioner_uuid" aria-label="Profesional"><option value="">Seleccionar profesional</option>{catalog.practitioners.map(item=><option key={item.uuid} value={item.uuid}>{item.name}</option>)}</select><select name="facility_uuid" aria-label="Instalación"><option value="">Seleccionar instalación</option>{catalog.facilities.map(item=><option key={item.uuid} value={item.uuid}>{item.name}</option>)}</select><input name="contact_name" placeholder="Nombre de contacto"/><input name="role" placeholder="Rol clínico" required/><input name="provider_since" type="date"/><button>Agregar participante</button></form></details>)}<details><summary>Nuevo equipo</summary><form className="care-team-form" onSubmit={create}><input name="name" aria-label="Nombre del equipo" placeholder="Nombre del equipo" required/><textarea name="note" aria-label="Nota del equipo" placeholder="Propósito o alcance"/><button>Crear equipo</button></form></details>{error&&<p className="error">{error}</p>}</section>;
}
