import { FormEvent, useEffect, useState } from "react";
import type { ApiRequest } from "../../api/client";
import type { Patient } from "./types";

type Candidate={patient:Patient;score:number;matched_fields:string[]};
type Preview={source:Patient;target:Patient;duplicate_score:number;matched_fields:string[];record_counts:Record<string,number>;conflicts:{type:string;resolution:string}[]};
type MergeEvidence={uuid:string;source_uuid:string;target_uuid:string;reason:string;duplicate_score:number;moved_counts:Record<string,number>;resolved_conflicts:{type:string;resolution:string}[];created_at:string};

export function PatientDuplicates({api,patientUuid,onOpen}:{api:ApiRequest;patientUuid:string;onOpen:(patient:Patient)=>void}){
  const [items,setItems]=useState<Candidate[]>([]); const [history,setHistory]=useState<MergeEvidence[]>([]); const [preview,setPreview]=useState<Preview|null>(null); const [error,setError]=useState("");
  useEffect(()=>{let cancelled=false;setItems([]);setHistory([]);setPreview(null);Promise.all([api<Candidate[]>(`/api/v1/patients/${patientUuid}/duplicate-candidates`),api<MergeEvidence[]>(`/api/v1/patients/${patientUuid}/merges`)]).then(([candidates,merges])=>{if(!cancelled){setItems(candidates);setHistory(merges)}}).catch(reason=>{if(!cancelled)setError(reason instanceof Error?reason.message:"Duplicate review could not be loaded")});return()=>{cancelled=true};},[patientUuid]);
  async function prepare(target:Patient){try{setError("");setPreview(await api<Preview>(`/api/v1/patients/${patientUuid}/merge-preview/${target.uuid}`));}catch(reason){setError(reason instanceof Error?reason.message:"Merge preview could not be loaded");}}
  async function merge(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!preview)return;const form=new FormData(event.currentTarget);try{setError("");await api(`/api/v1/patients/${patientUuid}/merge`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({target_patient_uuid:preview.target.uuid,confirmation:form.get("confirmation"),reason:form.get("reason")})});onOpen(preview.target);}catch(reason){setError(reason instanceof Error?reason.message:"Charts could not be merged");}}
  return <section className="summary-group duplicate-review"><h3>Possible duplicates<span>{items.length}</span></h3>{error&&<p className="error">{error}</p>}{items.map(item=><article key={item.patient.uuid}><strong>{item.patient.last_name}, {item.patient.first_name}</strong><small>{item.patient.date_of_birth} · score {item.score}/100 · {item.matched_fields.join(", ")}</small><button className="text-button" onClick={()=>onOpen(item.patient)}>Review chart</button><button className="text-button" onClick={()=>void prepare(item.patient)}>Prepare merge</button></article>)}{!items.length&&!error&&<p>No possible duplicates detected.</p>}<p className="portal-notice">Candidates require human review. No clinical records are merged automatically.</p>{preview&&<form className="quick-add compact" onSubmit={merge}><h4>Permanent merge preview</h4><p>The current chart ({preview.source.uuid}) will be retired. {preview.target.first_name} {preview.target.last_name} ({preview.target.uuid}) will remain canonical.</p><p>{Object.entries(preview.record_counts).map(([name,count])=>`${name}: ${count}`).join(" · ")||"No dependent records"}</p>{preview.conflicts.map((item,index)=><small key={`${item.type}-${index}`}>{item.type}: {item.resolution}</small>)}<label>Reason<input name="reason" minLength={10} maxLength={500} required/></label><label>Type the retained chart UUID<input name="confirmation" required pattern={preview.target.uuid} aria-label="Retained chart UUID"/></label><button>Merge permanently</button><button type="button" className="secondary" onClick={()=>setPreview(null)}>Cancel</button></form>}<h4>Merge history</h4>{history.map(item=><article key={item.uuid}><strong>Retired {item.source_uuid}</strong><small>{new Date(item.created_at).toLocaleString()} · score {item.duplicate_score}/100 · {item.reason}</small></article>)}{!history.length&&<p>No chart merges recorded.</p>}</section>;
}
