import { FormEvent, useEffect, useState } from "react";
import type { ApiRequest } from "../../api/client";

type Preference={uuid:string;category:string;observation_code:string;observation_code_text?:string;value_type:"coded"|"text"|"boolean";value_code?:string;value_code_system?:string;value_display?:string;value_text?:string;value_boolean?:boolean;effective_at:string;status:string;note?:string;amendment_reason?:string;supersedes_uuid?:string;active:boolean;inactivated_reason?:string};
type Observation={code:string;display:string};type Answer={answer_code:string;answer_system:string;answer_display:string};type Catalog={observations:Record<string,Observation[]>;answers:Record<string,Answer[]>};

function displayValue(item:Preference){return item.value_type==="coded"?`${item.value_display} (${item.value_code})`:item.value_type==="boolean"?(item.value_boolean?"Sí":"No"):item.value_text;}

export function PatientPreferencesWorkspace({api,patientUuid}:{api:ApiRequest;patientUuid:string}){
  const base=`/api/v1/patients/${patientUuid}/preferences`;const [items,setItems]=useState<Preference[]>([]),[catalog,setCatalog]=useState<Catalog>({observations:{},answers:{}}),[history,setHistory]=useState(false),[category,setCategory]=useState("treatment-intervention"),[observation,setObservation]=useState("81329-5"),[valueType,setValueType]=useState<"coded"|"text"|"boolean">("coded"),[error,setError]=useState("");
  async function load(showHistory=history){try{const [records,options]=await Promise.all([api<Preference[]>(`${base}?include_history=${showHistory}`),api<Catalog>(`/api/v1/patients/${patientUuid}/preference-catalog`)]);setItems(records);setCatalog(options);}catch(reason){setError(reason instanceof Error?reason.message:"No se pudieron cargar las preferencias");}}
  useEffect(()=>{void load();},[patientUuid]);
  function selectCategory(next:string){setCategory(next);setObservation(catalog.observations[next]?.[0]?.code??(next==="care-experience"?"95541-9":"81329-5"));}
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form),definition=catalog.observations[category]?.find(item=>item.code===observation),answer=catalog.answers[observation]?.find(item=>item.answer_code===data.get("value_code"));const body:any={category,observation_code:observation,observation_code_text:definition?.display??null,value_type:valueType,effective_at:new Date().toISOString(),status:data.get("status"),note:data.get("note")||null};if(valueType==="coded")Object.assign(body,{value_code:data.get("value_code"),value_code_system:answer?.answer_system||data.get("value_code_system"),value_display:answer?.answer_display||data.get("value_display")});else if(valueType==="text")body.value_text=data.get("value_text");else body.value_boolean=data.get("value_boolean")==="true";try{await api(base,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});form.reset();await load();}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo registrar la preferencia");}}
  async function amend(item:Preference){const reason=window.prompt("Motivo de la enmienda");if(!reason)return;const entered=window.prompt("Nuevo valor",String(displayValue(item)??""));if(entered===null)return;const body:any={category:item.category,observation_code:item.observation_code,observation_code_text:item.observation_code_text??null,value_type:item.value_type,effective_at:new Date().toISOString(),status:"final",note:item.note??null,amendment_reason:reason};if(item.value_type==="coded")Object.assign(body,{value_code:item.value_code,value_code_system:item.value_code_system,value_display:entered});else if(item.value_type==="text")body.value_text=entered;else body.value_boolean=/^(true|yes|sí|si|1)$/i.test(entered);try{await api(`${base}/${item.uuid}/amend`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});await load();}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo enmendar la preferencia");}}
  async function inactivate(item:Preference){const reason=window.prompt("Motivo del retiro");if(!reason)return;try{await api(`${base}/${item.uuid}?reason=${encodeURIComponent(reason)}`,{method:"DELETE"});await load();}catch(cause){setError(cause instanceof Error?cause.message:"No se pudo retirar la preferencia");}}
  const observations=catalog.observations[category]??[],answers=catalog.answers[observation]??[];
  return <section className="summary-group preference-workspace"><h3>Preferencias clínicas<span>{items.filter(item=>item.active).length}</span></h3><label className="history-toggle"><input type="checkbox" checked={history} onChange={event=>{setHistory(event.target.checked);void load(event.target.checked);}}/> Mostrar historial</label>{items.map(item=><article key={item.uuid} className={!item.active?"historical":""}><strong>{item.observation_code_text||item.observation_code}</strong><small>{displayValue(item)} · {item.status} · {new Date(item.effective_at).toLocaleString()}{item.amendment_reason?` · ${item.amendment_reason}`:""}</small>{item.active&&<div><button type="button" className="text-button" onClick={()=>void amend(item)}>Enmendar</button><button type="button" className="text-button" onClick={()=>void inactivate(item)}>Retirar</button></div>}</article>)}<details><summary>Nueva preferencia</summary><form className="preference-form" onSubmit={create}><select aria-label="Categoría de preferencia" value={category} onChange={event=>selectCategory(event.target.value)}><option value="treatment-intervention">Intervenciones de tratamiento</option><option value="care-experience">Experiencia de atención</option></select><select aria-label="Observación LOINC" value={observation} onChange={event=>setObservation(event.target.value)}>{observations.map(item=><option key={item.code} value={item.code}>{item.display} · {item.code}</option>)}</select><select aria-label="Tipo de valor" value={valueType} onChange={event=>setValueType(event.target.value as typeof valueType)}><option value="coded">Codificado</option><option value="text">Texto</option><option value="boolean">Sí/No</option></select>{valueType==="coded"&&(answers.length?<select name="value_code" aria-label="Respuesta codificada" required><option value="">Seleccionar respuesta</option>{answers.map(item=><option key={`${item.answer_system}-${item.answer_code}`} value={item.answer_code}>{item.answer_display}</option>)}</select>:<><input name="value_code" placeholder="Código de respuesta" required/><input name="value_code_system" placeholder="Sistema de códigos" required/><input name="value_display" placeholder="Respuesta" required/></>)}{valueType==="text"&&<textarea name="value_text" aria-label="Valor de preferencia" required/>}{valueType==="boolean"&&<select name="value_boolean" aria-label="Valor sí o no"><option value="true">Sí</option><option value="false">No</option></select>}<select name="status" aria-label="Estado"><option value="final">Final</option><option value="preliminary">Preliminar</option></select><textarea name="note" placeholder="Nota clínica"/><button>Registrar preferencia</button></form></details>{error&&<p className="error">{error}</p>}</section>;
}
