import {FormEvent,useEffect,useState} from "react";
import type {ApiRequest} from "../../api/client";

type Assignment={uuid:string;practitioner_name?:string;facility_name?:string;role:string;status:string;assigned_at?:string;ended_at?:string;source:string};
type Catalog={practitioners:{uuid:string;name:string}[];facilities:{uuid:string;name:string}[]};

export function PatientProviderAssignments({api,patientUuid}:{api:ApiRequest;patientUuid:string}){
  const [items,setItems]=useState<Assignment[]>([]);const [catalog,setCatalog]=useState<Catalog>({practitioners:[],facilities:[]});const [open,setOpen]=useState(false);const [error,setError]=useState("");
  async function load(){try{const [records,options]=await Promise.all([api<Assignment[]>(`/api/v1/patients/${patientUuid}/provider-assignments`),api<Catalog>(`/api/v1/patients/${patientUuid}/provider-assignments/catalog`)]);setItems(records);setCatalog(options);setError("");}catch(reason){setError(reason instanceof Error?reason.message:"No se pudieron cargar las asignaciones");}}
  useEffect(()=>{void load();},[patientUuid]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);try{await api(`/api/v1/patients/${patientUuid}/provider-assignments`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({practitioner_uuid:form.get("practitioner_uuid"),facility_uuid:form.get("facility_uuid")||null,role:form.get("role")})});setOpen(false);await load();}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo crear la asignación");}}
  async function end(item:Assignment){try{await api(`/api/v1/patients/${patientUuid}/provider-assignments/${item.uuid}`,{method:"DELETE"});await load();}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo finalizar la asignación");}}
  const labels:Record<string,string>={primary:"Principal",referring:"Referente",consulting:"Consultor",covering:"Cobertura"};
  return <section className="summary-group"><h3>Profesionales asignados<span>{items.filter(x=>x.status==="active").length}</span></h3><button className="text-button" onClick={()=>setOpen(value=>!value)}>{open?"Cancelar":"Asignar profesional"}</button>{open&&<form className="quick-add compact" onSubmit={submit}><select name="practitioner_uuid" aria-label="Profesional" required><option value="">Profesional</option>{catalog.practitioners.map(x=><option key={x.uuid} value={x.uuid}>{x.name}</option>)}</select><select name="facility_uuid" aria-label="Instalación"><option value="">Instalación principal</option>{catalog.facilities.map(x=><option key={x.uuid} value={x.uuid}>{x.name}</option>)}</select><select name="role" aria-label="Rol" defaultValue="primary"><option value="primary">Principal</option><option value="referring">Referente</option><option value="consulting">Consultor</option><option value="covering">Cobertura</option></select><button>Guardar asignación</button></form>}{error&&<p className="error">{error}</p>}{items.map(item=><article key={item.uuid}><strong>{item.practitioner_name||"Profesional legacy"}</strong><small>{labels[item.role]||item.role} · {item.facility_name||"Sin instalación"} · {item.status}{item.source==="patient_data"?" · importado":""}</small>{item.assigned_at&&<small>Desde {new Date(item.assigned_at).toLocaleDateString()}</small>}{item.status==="active"&&<button className="text-button" onClick={()=>void end(item)}>Finalizar</button>}</article>)}</section>;
}
