import {FormEvent,useEffect,useState} from "react";
import type {ApiRequest} from "../../api/client";
type Referral={uuid:string;recipient_name:string;recipient_organization?:string;referred_at:string;reason:string;status:string;replied_at?:string;reply?:string};
export function ReferralWorkspace({api,patientUuid}:{api:ApiRequest;patientUuid:string}){
 const [items,setItems]=useState<Referral[]>([]),[error,setError]=useState("");const base=`/api/v1/patients/${patientUuid}/referrals`;
 const load=()=>api<Referral[]>(base).then(rows=>setItems([...rows])).catch(e=>setError(e instanceof Error?e.message:"Could not load referrals"));useEffect(()=>{void load()},[patientUuid]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f);try{await api(base,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({recipient_name:d.get("recipient_name"),recipient_organization:d.get("recipient_organization")||null,referred_at:new Date(String(d.get("referred_at"))).toISOString(),reason:d.get("reason")})});f.reset();await load()}catch(x){setError(x instanceof Error?x.message:"Could not create referral")}}
 async function reply(item:Referral){const text=window.prompt("Specialist reply");if(!text)return;try{await api(`${base}/${item.uuid}/reply`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({replied_at:new Date().toISOString(),reply:text})});await load()}catch(x){setError(x instanceof Error?x.message:"Could not close referral")}}
 return <section className="summary-group"><h3>Referrals<span>{items.length}</span></h3>{items.map(x=><article key={x.uuid}><strong>{x.recipient_organization||x.recipient_name}</strong><small>{new Date(x.referred_at).toLocaleDateString()} · {x.status}</small><p>{x.reason}</p>{x.reply?<p>{x.reply}</p>:<button type="button" onClick={()=>void reply(x)}>Record reply</button>}</article>)}<details><summary>New referral</summary><form className="quick-add" onSubmit={create}><input name="recipient_name" placeholder="Recipient" required/><input name="recipient_organization" placeholder="Organization"/><input name="referred_at" type="datetime-local" required/><textarea name="reason" placeholder="Reason" required/><button>Create referral</button></form></details>{error&&<p className="error">{error}</p>}</section>
}
