import {FormEvent,useEffect,useState} from "react";
import type {ApiRequest} from "../../api/client";

type SocialHistory={uuid:string;recorded_at?:string;tobacco?:string;alcohol?:string;recreational_drugs?:string;exercise_patterns?:string;additional_history?:string;legacy_history_id?:number};

export function SocialHistoryWorkspace({api,patientUuid}:{api:ApiRequest;patientUuid:string}){
  const [items,setItems]=useState<SocialHistory[]>([]);const [open,setOpen]=useState(false);const [error,setError]=useState("");
  async function load(){try{setItems(await api<SocialHistory[]>(`/api/v1/patients/${patientUuid}/social-history`));setError("");}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo cargar la historia social");}}
  useEffect(()=>{void load();},[patientUuid]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const element=event.currentTarget;const form=new FormData(element);const body=Object.fromEntries(["tobacco","alcohol","recreational_drugs","exercise_patterns","additional_history"].map(key=>[key,form.get(key)||null]));try{await api(`/api/v1/patients/${patientUuid}/social-history`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});element.reset();setOpen(false);await load();}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo registrar la historia social");}}
  return <section className="summary-group"><h3>Historia social<span>{items.length}</span></h3><button className="text-button" onClick={()=>setOpen(value=>!value)}>{open?"Cancelar":"Nueva versión"}</button>{open&&<form className="quick-add compact" onSubmit={submit}><input name="tobacco" aria-label="Tabaco" placeholder="Tabaco"/><input name="alcohol" aria-label="Alcohol" placeholder="Alcohol"/><input name="recreational_drugs" aria-label="Drogas recreativas" placeholder="Drogas recreativas"/><input name="exercise_patterns" aria-label="Ejercicio" placeholder="Ejercicio"/><textarea name="additional_history" aria-label="Historia adicional" placeholder="Historia adicional"/><button>Registrar historia</button></form>}{error&&<p className="error">{error}</p>}{items.map(item=><article key={item.uuid}><strong>{item.tobacco||item.alcohol||item.additional_history||"Historia social registrada"}</strong><small>{item.recorded_at?new Date(item.recorded_at).toLocaleString():"Fecha original no disponible"}{item.legacy_history_id?` · referencia ${item.legacy_history_id}`:""}</small>{item.exercise_patterns&&<small>Ejercicio: {item.exercise_patterns}</small>}{item.recreational_drugs&&<small>Drogas recreativas: {item.recreational_drugs}</small>}</article>)}</section>;
}
