"""Complete portal questionnaires, notifications and staff messaging."""
from alembic import op
import sqlalchemy as sa

revision="20261108_0069";down_revision="20261107_0068";branch_labels=None;depends_on=None


def upgrade():
    bind=op.get_bind();inspector=sa.inspect(bind);tables=set(inspector.get_table_names())
    delivery_columns={column["name"]:column for column in inspector.get_columns("communication_deliveries")}
    if "legacy_notification_id" not in delivery_columns:op.add_column("communication_deliveries",sa.Column("legacy_notification_id",sa.Integer(),nullable=True,unique=True))
    response_columns={column["name"]:column for column in inspector.get_columns("questionnaire_responses")}
    definition_columns={column["name"]:column for column in inspector.get_columns("questionnaire_definitions")}
    if "legacy_questionnaire_id" not in definition_columns:op.add_column("questionnaire_definitions",sa.Column("legacy_questionnaire_id",sa.Integer(),nullable=True,unique=True))
    if "legacy_payload" not in definition_columns:op.add_column("questionnaire_definitions",sa.Column("legacy_payload",sa.JSON(),nullable=True))
    if "legacy_response_id" not in response_columns:op.add_column("questionnaire_responses",sa.Column("legacy_response_id",sa.Integer(),nullable=True,unique=True))
    if "status" not in response_columns:op.add_column("questionnaire_responses",sa.Column("status",sa.String(20),nullable=False,server_default="completed"));op.create_index("ix_questionnaire_responses_status","questionnaire_responses",["status"])
    if "legacy_payload" not in response_columns:op.add_column("questionnaire_responses",sa.Column("legacy_payload",sa.JSON(),nullable=True))
    if not response_columns["author_id"]["nullable"]:op.alter_column("questionnaire_responses","author_id",existing_type=sa.Integer(),nullable=True)
    if "author_portal_account_id" not in response_columns:
        op.add_column("questionnaire_responses",sa.Column("author_portal_account_id",sa.Integer(),sa.ForeignKey("portal_accounts.id"),nullable=True));op.create_index("ix_questionnaire_responses_author_portal_account_id","questionnaire_responses",["author_portal_account_id"])
    if "notification_preferences" not in tables:
        op.create_table("notification_preferences",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("uuid",sa.String(36),nullable=False),sa.Column("portal_account_id",sa.Integer(),sa.ForeignKey("portal_accounts.id"),nullable=False),sa.Column("patient_id",sa.Integer(),sa.ForeignKey("patients.id"),nullable=False),sa.Column("email_enabled",sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column("sms_enabled",sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column("in_app_enabled",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("message_events",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("appointment_events",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("result_events",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("questionnaire_events",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("timezone_name",sa.String(64),nullable=False,server_default="UTC"),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("portal_account_id","patient_id",name="uq_notification_preference_context"))
        for column in ("uuid","portal_account_id","patient_id"):op.create_index(f"ix_notification_preferences_{column}","notification_preferences",[column],unique=column=="uuid")
    if "portal_notifications" not in tables:
        op.create_table("portal_notifications",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("uuid",sa.String(36),nullable=False),sa.Column("portal_account_id",sa.Integer(),sa.ForeignKey("portal_accounts.id"),nullable=False),sa.Column("patient_id",sa.Integer(),sa.ForeignKey("patients.id"),nullable=False),sa.Column("event_type",sa.String(30),nullable=False),sa.Column("title",sa.String(255),nullable=False),sa.Column("body",sa.Text(),nullable=False),sa.Column("action_url",sa.String(500),nullable=True),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("read_at",sa.DateTime(timezone=True),nullable=True),sa.Column("dismissed_at",sa.DateTime(timezone=True),nullable=True))
        for column in ("uuid","portal_account_id","patient_id","event_type","created_at","read_at","dismissed_at"):op.create_index(f"ix_portal_notifications_{column}","portal_notifications",[column],unique=column=="uuid")
    if "staff_message_threads" not in tables:
        op.create_table("staff_message_threads",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("uuid",sa.String(36),nullable=False),sa.Column("subject",sa.String(255),nullable=False),sa.Column("created_by_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("status",sa.String(20),nullable=False,server_default="open"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
        for column in ("uuid","created_by_id","status","updated_at"):op.create_index(f"ix_staff_message_threads_{column}","staff_message_threads",[column],unique=column=="uuid")
    if "staff_thread_participants" not in tables:
        op.create_table("staff_thread_participants",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("thread_id",sa.Integer(),sa.ForeignKey("staff_message_threads.id"),nullable=False),sa.Column("user_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("role",sa.String(20),nullable=False,server_default="member"),sa.Column("read_at",sa.DateTime(timezone=True),nullable=True),sa.UniqueConstraint("thread_id","user_id",name="uq_staff_thread_participant"));op.create_index("ix_staff_thread_participants_thread_id","staff_thread_participants",["thread_id"]);op.create_index("ix_staff_thread_participants_user_id","staff_thread_participants",["user_id"])
    if "staff_messages" not in tables:
        op.create_table("staff_messages",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("uuid",sa.String(36),nullable=False),sa.Column("thread_id",sa.Integer(),sa.ForeignKey("staff_message_threads.id"),nullable=False),sa.Column("sender_user_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("body",sa.Text(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("deleted_at",sa.DateTime(timezone=True),nullable=True))
        for column in ("uuid","thread_id","sender_user_id","created_at"):op.create_index(f"ix_staff_messages_{column}","staff_messages",[column],unique=column=="uuid")
    if "questionnaire_assignments" not in tables:
        op.create_table("questionnaire_assignments",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("uuid",sa.String(36),nullable=False),sa.Column("patient_id",sa.Integer(),sa.ForeignKey("patients.id"),nullable=False),sa.Column("questionnaire_id",sa.Integer(),sa.ForeignKey("questionnaire_definitions.id"),nullable=False),sa.Column("assigned_by_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("response_id",sa.Integer(),sa.ForeignKey("questionnaire_responses.id"),nullable=True,unique=True),sa.Column("instructions",sa.Text(),nullable=True),sa.Column("status",sa.String(20),nullable=False,server_default="assigned"),sa.Column("assigned_at",sa.DateTime(timezone=True),nullable=False),sa.Column("due_at",sa.DateTime(timezone=True),nullable=True),sa.Column("completed_at",sa.DateTime(timezone=True),nullable=True),sa.Column("cancelled_at",sa.DateTime(timezone=True),nullable=True))
        for column in ("uuid","patient_id","questionnaire_id","assigned_by_id","status","assigned_at","due_at"):op.create_index(f"ix_questionnaire_assignments_{column}","questionnaire_assignments",[column],unique=column=="uuid")


def downgrade():
    for table in ("questionnaire_assignments","staff_messages","staff_thread_participants","staff_message_threads","portal_notifications","notification_preferences"):op.drop_table(table)
    op.drop_index("ix_questionnaire_responses_status",table_name="questionnaire_responses");op.drop_index("ix_questionnaire_responses_author_portal_account_id",table_name="questionnaire_responses");op.drop_column("questionnaire_responses","legacy_payload");op.drop_column("questionnaire_responses","status");op.drop_column("questionnaire_responses","legacy_response_id");op.drop_column("questionnaire_responses","author_portal_account_id");op.alter_column("questionnaire_responses","author_id",existing_type=sa.Integer(),nullable=False);op.drop_column("questionnaire_definitions","legacy_payload");op.drop_column("questionnaire_definitions","legacy_questionnaire_id");op.drop_column("communication_deliveries","legacy_notification_id")
