"""Complete SMART interactive authorization and launch context."""
from alembic import op
import sqlalchemy as sa

revision="20261104_0065";down_revision="20261103_0064";branch_labels=None;depends_on=None


def upgrade():
    op.add_column("smart_clients",sa.Column("client_kind",sa.String(30),nullable=False,server_default="backend"));op.add_column("smart_clients",sa.Column("redirect_uris",sa.JSON(),nullable=False,server_default="[]"));op.add_column("smart_clients",sa.Column("launch_uri",sa.String(1000),nullable=True));op.add_column("smart_clients",sa.Column("launch_types",sa.JSON(),nullable=False,server_default="[]"));op.alter_column("smart_clients","jwks",nullable=True);op.create_index("ix_smart_clients_client_kind","smart_clients",["client_kind"])
    op.add_column("auth_sessions",sa.Column("smart_patient_id",sa.Integer(),sa.ForeignKey("patients.id"),nullable=True));op.add_column("auth_sessions",sa.Column("smart_encounter_id",sa.Integer(),sa.ForeignKey("encounters.id"),nullable=True));op.create_index("ix_auth_sessions_smart_patient_id","auth_sessions",["smart_patient_id"]);op.create_index("ix_auth_sessions_smart_encounter_id","auth_sessions",["smart_encounter_id"])
    op.create_table("smart_launch_contexts",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("uuid",sa.String(36),nullable=False),sa.Column("token_hash",sa.String(64),nullable=False),sa.Column("smart_client_id",sa.Integer(),sa.ForeignKey("smart_clients.id"),nullable=False),sa.Column("identity_kind",sa.String(20),nullable=False),sa.Column("patient_id",sa.Integer(),sa.ForeignKey("patients.id"),nullable=True),sa.Column("encounter_id",sa.Integer(),sa.ForeignKey("encounters.id"),nullable=True),sa.Column("created_by_user_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=True),sa.Column("created_by_portal_account_id",sa.Integer(),sa.ForeignKey("portal_accounts.id"),nullable=True),sa.Column("expires_at",sa.DateTime(timezone=True),nullable=False),sa.Column("consumed_at",sa.DateTime(timezone=True),nullable=True))
    for column in ("uuid","token_hash","smart_client_id","identity_kind","patient_id","encounter_id","expires_at"):op.create_index(f"ix_smart_launch_contexts_{column}","smart_launch_contexts",[column],unique=column in {"uuid","token_hash"})
    op.create_table("smart_authorization_requests",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("uuid",sa.String(36),nullable=False),sa.Column("request_hash",sa.String(64),nullable=False),sa.Column("smart_client_id",sa.Integer(),sa.ForeignKey("smart_clients.id"),nullable=False),sa.Column("launch_context_id",sa.Integer(),sa.ForeignKey("smart_launch_contexts.id"),nullable=True),sa.Column("redirect_uri",sa.String(1000),nullable=False),sa.Column("scopes",sa.JSON(),nullable=False),sa.Column("state",sa.String(500),nullable=False),sa.Column("audience",sa.String(1000),nullable=False),sa.Column("nonce",sa.String(500),nullable=True),sa.Column("code_challenge",sa.String(128),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("expires_at",sa.DateTime(timezone=True),nullable=False),sa.Column("consumed_at",sa.DateTime(timezone=True),nullable=True))
    for column in ("uuid","request_hash","smart_client_id","expires_at"):op.create_index(f"ix_smart_authorization_requests_{column}","smart_authorization_requests",[column],unique=column in {"uuid","request_hash"})
    op.create_table("smart_authorization_codes",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("code_hash",sa.String(64),nullable=False),sa.Column("smart_client_id",sa.Integer(),sa.ForeignKey("smart_clients.id"),nullable=False),sa.Column("authorization_request_id",sa.Integer(),sa.ForeignKey("smart_authorization_requests.id"),nullable=False,unique=True),sa.Column("user_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=True),sa.Column("portal_account_id",sa.Integer(),sa.ForeignKey("portal_accounts.id"),nullable=True),sa.Column("patient_id",sa.Integer(),sa.ForeignKey("patients.id"),nullable=True),sa.Column("encounter_id",sa.Integer(),sa.ForeignKey("encounters.id"),nullable=True),sa.Column("redirect_uri",sa.String(1000),nullable=False),sa.Column("scopes",sa.JSON(),nullable=False),sa.Column("nonce",sa.String(500),nullable=True),sa.Column("code_challenge",sa.String(128),nullable=False),sa.Column("expires_at",sa.DateTime(timezone=True),nullable=False),sa.Column("consumed_at",sa.DateTime(timezone=True),nullable=True))
    for column in ("code_hash","smart_client_id","expires_at"):op.create_index(f"ix_smart_authorization_codes_{column}","smart_authorization_codes",[column],unique=column=="code_hash")


def downgrade():
    op.drop_table("smart_authorization_codes");op.drop_table("smart_authorization_requests");op.drop_table("smart_launch_contexts");op.drop_index("ix_auth_sessions_smart_encounter_id",table_name="auth_sessions");op.drop_index("ix_auth_sessions_smart_patient_id",table_name="auth_sessions");op.drop_column("auth_sessions","smart_encounter_id");op.drop_column("auth_sessions","smart_patient_id");op.drop_index("ix_smart_clients_client_kind",table_name="smart_clients");op.drop_column("smart_clients","launch_types");op.drop_column("smart_clients","launch_uri");op.drop_column("smart_clients","redirect_uris");op.alter_column("smart_clients","jwks",nullable=False);op.drop_column("smart_clients","client_kind")
