import { FormEvent, useEffect, useState } from "react";
import type { ApiRequest } from "../../api/client";

type Product={uuid:string;name:string;ndc_number?:string;on_hand:number;reorder_point:string;active:boolean};
type Lot={uuid:string;lot_number?:string;expiration?:string;warehouse_id:string;manufacturer?:string;on_hand:number;destroyed_at?:string};

export function InventoryWorkspace({api}:{api:ApiRequest}){
  const [products,setProducts]=useState<Product[]>([]); const [selected,setSelected]=useState<Product|null>(null); const [lots,setLots]=useState<Lot[]>([]); const [error,setError]=useState("");
  async function loadProducts(){try{const rows=await api<Product[]>("/api/v1/inventory/products");setProducts(rows);if(selected)setSelected(rows.find(row=>row.uuid===selected.uuid)??null);setError("");}catch(reason){setError(reason instanceof Error?reason.message:"Could not load inventory");}}
  async function open(product:Product){setSelected(product);try{setLots(await api<Lot[]>(`/api/v1/inventory/products/${product.uuid}/lots`));}catch(reason){setError(reason instanceof Error?reason.message:"Could not load lots");}}
  useEffect(()=>{void loadProducts();},[]);
  async function createProduct(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=new FormData(form);try{await api("/api/v1/inventory/products",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:data.get("name"),ndc_number:data.get("ndc_number")||null,reorder_point:Number(data.get("reorder_point")||0),allow_combining:data.get("allow_combining")==="on"})});form.reset();await loadProducts();}catch(reason){setError(reason instanceof Error?reason.message:"Could not save product");}}
  async function createLot(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;const form=event.currentTarget;const data=new FormData(form);try{await api(`/api/v1/inventory/products/${selected.uuid}/lots`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({lot_number:data.get("lot_number")||null,expiration:data.get("expiration")||null,warehouse_id:data.get("warehouse_id"),manufacturer:data.get("manufacturer")||null,opening_quantity:Number(data.get("opening_quantity"))})});form.reset();await open(selected);await loadProducts();}catch(reason){setError(reason instanceof Error?reason.message:"Could not save lot");}}
  return <section className="inventory-workspace"><form className="card inventory-form" onSubmit={createProduct}><h2>Add product</h2><div className="form-grid"><label>Name<input name="name" required maxLength={255}/></label><label>NDC<input name="ndc_number" maxLength={20}/></label><label>Reorder point<input name="reorder_point" type="number" min="0" step="0.001" defaultValue="0"/></label><label className="check"><input name="allow_combining" type="checkbox"/> Allow combining lots</label></div><button>Add product</button></form>{error&&<p className="error">{error}</p>}<div className={selected?"inventory-grid selected":"inventory-grid"}><section className="card"><h2 className="padded-title">Products</h2><table><thead><tr><th>Product</th><th>NDC</th><th>On hand</th></tr></thead><tbody>{products.map(product=><tr key={product.uuid} onClick={()=>void open(product)} className="patient-row"><td><strong>{product.name}</strong></td><td>{product.ndc_number??"—"}</td><td className={product.on_hand<=Number(product.reorder_point)?"low-stock":""}>{product.on_hand}</td></tr>)}</tbody></table>{!products.length&&<div className="empty">No inventory products.</div>}</section>{selected&&<section className="card inventory-detail"><h2>{selected.name}</h2><form className="quick-add" onSubmit={createLot}><h3>Add lot / opening stock</h3><input name="lot_number" placeholder="Lot number"/><input name="expiration" aria-label="Expiration" type="date"/><input name="warehouse_id" placeholder="Warehouse" required/><input name="manufacturer" placeholder="Manufacturer"/><input name="opening_quantity" aria-label="Opening quantity" type="number" min="0" defaultValue="0" required/><button>Add lot</button></form><h3>Active lots</h3>{lots.map(lot=><article className="lot-row" key={lot.uuid}><strong>{lot.lot_number??"No lot number"}</strong><span>{lot.on_hand} on hand</span><small>{lot.warehouse_id||"Default warehouse"} · {lot.expiration??"No expiration"}</small></article>)}</section>}</div></section>;
}
