import React, { FormEvent, useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";
import "./clinical.css";

const API = import.meta.env.VITE_API_URL ?? "http://localhost:8000";
type Patient = { uuid:string; first_name:string; last_name:string; date_of_birth:string; sex:string; email?:string };
type Item = { uuid:string; title:string; status:string; code?:string; reaction?:string; dosage?:string };
type Summary = { patient:Patient; problems:Item[]; allergies:Item[]; medications:Item[]; encounters:{uuid:string;occurred_at:string;chief_complaint?:string}[] };

function Login({done}:{done:(token:string)=>void}) {
  const [error,setError]=useState("");
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);const r=await fetch(`${API}/api/v1/auth/token`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:d.get("email"),password:d.get("password")})});if(!r.ok)return setError("Credenciales inválidas");const body=await r.json();localStorage.setItem("token",body.access_token);done(body.access_token)}
  return <main className="login"><form onSubmit={submit}><p className="eyebrow">OPENEMR NEXT</p><h1>Expediente clínico</h1><label>Correo<input name="email" type="email" defaultValue="admin@example.com" required/></label><label>Contraseña<input name="password" type="password" defaultValue="change-me-now" required/></label>{error&&<p className="error">{error}</p>}<button>Ingresar</button></form></main>
}

function Group({title,items}:{title:string;items:Item[]}){return <section className="summary-group"><h3>{title} <span>{items.length}</span></h3>{items.length?items.map(x=><article key={x.uuid}><strong>{x.title}</strong><small>{x.code||x.reaction||x.dosage||x.status}</small></article>):<p>Sin registros activos</p>}</section>}

function App(){
  const [token,setToken]=useState(localStorage.getItem("token")??"");const [patients,setPatients]=useState<Patient[]>([]);const [query,setQuery]=useState("");const [selected,setSelected]=useState<Summary|null>(null);
  async function api(path:string,init:RequestInit={}){const r=await fetch(`${API}${path}`,{...init,headers:{Authorization:`Bearer ${token}`,...(init.headers??{})}});if(r.status===401){localStorage.removeItem("token");setToken("");throw Error("Unauthorized")}if(!r.ok)throw Error((await r.json()).detail);return r.json()}
  async function load(q=query){setPatients((await api(`/api/v1/patients?q=${encodeURIComponent(q)}`)).items)}async function open(p:Patient){setSelected(await api(`/api/v1/patients/${p.uuid}/summary`))}
  async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;const d=new FormData(e.currentTarget);await api(`/api/v1/patients/${selected.patient.uuid}/clinical-items`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({category:d.get("category"),title:d.get("title")})});e.currentTarget.reset();await open(selected.patient)}
  useEffect(()=>{if(token)void load("")},[token]);if(!token)return <Login done={setToken}/>;
  return <div className="shell"><aside><div className="brand">OE</div><nav><a className="active">Pacientes</a><a>Agenda</a><a>Encuentros</a><a>Reportes</a></nav><button className="logout" onClick={()=>{localStorage.removeItem("token");setToken("")}}>Salir</button></aside><main><header><div><p className="eyebrow">ATENCIÓN CLÍNICA</p><h1>Pacientes</h1></div><button>+ Nuevo paciente</button></header><div className={selected?"workspace detail-open":"workspace"}><section className="card"><div className="toolbar"><input aria-label="Buscar pacientes" placeholder="Buscar por nombre o correo" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void load()}/><span>{patients.length} resultados</span></div><table><thead><tr><th>Paciente</th><th>Fecha de nacimiento</th><th>Sexo</th><th>Correo</th></tr></thead><tbody>{patients.map(p=><tr className="patient-row" key={p.uuid} onClick={()=>void open(p)}><td><strong>{p.last_name}, {p.first_name}</strong><small>{p.uuid.slice(0,8)}</small></td><td>{p.date_of_birth}</td><td>{p.sex}</td><td>{p.email??"—"}</td></tr>)}</tbody></table>{!patients.length&&<div className="empty">No hay pacientes que mostrar.</div>}</section>{selected&&<aside className="patient-drawer"><button className="close" onClick={()=>setSelected(null)}>×</button><p className="eyebrow">RESUMEN CLÍNICO</p><h2>{selected.patient.first_name} {selected.patient.last_name}</h2><p>{selected.patient.date_of_birth} · {selected.patient.sex}</p><Group title="Problemas" items={selected.problems}/><Group title="Alergias" items={selected.allergies}/><Group title="Medicamentos" items={selected.medications}/><section className="summary-group"><h3>Encuentros <span>{selected.encounters.length}</span></h3>{selected.encounters.map(x=><article key={x.uuid}><strong>{x.chief_complaint||"Encuentro clínico"}</strong><small>{new Date(x.occurred_at).toLocaleString()}</small></article>)}</section><form className="quick-add" onSubmit={add}><h3>Agregar al expediente</h3><select name="category"><option value="problem">Problema</option><option value="allergy">Alergia</option><option value="medication">Medicamento</option></select><input name="title" placeholder="Descripción" required/><button>Guardar</button></form></aside>}</div></main></div>
}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
