#!/usr/bin/env python3
"""Produce a deterministic, read-only legacy surface manifest.

The manifest is deliberately mechanical: it prevents future inventories from
silently forgetting a table, form, report, route, service, or scheduled command.
Semantic feature rows remain curated in docs/FUNCTIONAL_PARITY.md.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LEGACY = ROOT / "openemr-legacy"


def relative(paths: list[Path]) -> list[str]:
    return sorted(str(path.relative_to(LEGACY)) for path in paths)


def main() -> None:
    schema = (LEGACY / "sql/database.sql").read_text(errors="replace")
    table_pattern = re.compile(
        r"CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?`?([A-Za-z0-9_]+)`?", re.I
    )
    route_files = sorted((LEGACY / "apis/routes").glob("*.php"))
    route_pattern = re.compile(
        r"['\"]((?:GET|POST|PUT|PATCH|DELETE|OPTIONS)\s+[^'\"]+)['\"]\s*=>", re.I
    )
    permission_pattern = re.compile(
        r"request_authorization_check\(\s*\$request,\s*['\"]([^'\"]+)['\"],\s*['\"]([^'\"]+)['\"]",
        re.I,
    )

    manifest = {
        "source_version": "8.4.0-dev",
        "database_revision": 543,
        "tables": sorted(set(table_pattern.findall(schema))),
        "forms": relative([p for p in (LEGACY / "interface/forms").iterdir() if p.is_dir()]),
        "reports": relative(list((LEGACY / "interface/reports").glob("*.php"))),
        "services": relative(list((LEGACY / "src").rglob("*Service.php"))),
        "rest_route_files": relative(route_files),
        "rest_method_tokens": {
            str(path.relative_to(LEGACY)): len(route_pattern.findall(path.read_text(errors="replace")))
            for path in route_files
        },
        "rest_routes": {
            str(path.relative_to(LEGACY)): route_pattern.findall(path.read_text(errors="replace"))
            for path in route_files
        },
        "rest_acl_pairs": sorted(
            {
                f"{section}:{value}"
                for path in route_files
                for section, value in permission_pattern.findall(path.read_text(errors="replace"))
            }
        ),
        "commands": relative(
            list((LEGACY / "src/Common/Command").glob("*Command.php"))
            + list((LEGACY / "src/Console/Command").rglob("*Command.php"))
        ),
    }
    manifest["counts"] = {
        key: len(value)
        for key, value in manifest.items()
        if isinstance(value, (list, dict)) and key != "counts"
    }
    output = ROOT / "docs/legacy-surface.json"
    output.write_text(json.dumps(manifest, indent=2) + "\n")
    parity_path = ROOT / "docs/api-parity.json"
    parity = json.loads(parity_path.read_text()) if parity_path.exists() else {}
    api_inventory = [
        "# Legacy REST API inventory",
        "",
        "Generated by `scripts/audit_legacy.py`. Each route must be linked to a",
        "replacement contract test before API parity can be verified.",
        "",
        "| Legacy route map | Method and route | Replacement | Test | Status |",
        "|---|---|---|---|---|",
    ]
    for filename, routes in manifest["rest_routes"].items():
        for route in routes:
            item = parity.get(route, {})
            replacement = item.get("replacement", "—")
            test = item.get("test", "—")
            status = item.get("status", "NOT STARTED")
            api_inventory.append(
                f"| `{filename}` | `{route}` | `{replacement}` | `{test}` | {status} |"
            )
    (ROOT / "docs/LEGACY_API_INVENTORY.md").write_text("\n".join(api_inventory) + "\n")
    print(json.dumps(manifest["counts"], sort_keys=True))


if __name__ == "__main__":
    main()
