#!/usr/bin/env python3
"""Guard the SMART App Launch security contract."""
from pathlib import Path

root=Path(__file__).resolve().parents[1];models=(root/"backend/app/models.py").read_text();migration=(root/"backend/alembic/versions/20261103_0064_smart_backend_services.py").read_text();interactive_migration=(root/"backend/alembic/versions/20261104_0065_smart_interactive_launch.py").read_text();auth_migration=(root/"backend/alembic/versions/20260913_0013_auth_sessions.py").read_text();api=(root/"backend/app/api/smart.py").read_text();security=(root/"backend/app/security.py").read_text();fhir=(root/"backend/app/fhir.py").read_text();frontend=(root/"frontend/src/features/administration/AdministrationWorkspace.tsx").read_text();consent=(root/"frontend/src/features/smart/SmartAuthorizeApp.tsx").read_text();tests=(root/"backend/tests/test_smart_backend_services.py").read_text();interactive_tests=(root/"backend/tests/test_smart_interactive_launch.py").read_text()
checks=((models,"class SmartClient"),(models,"class SmartAssertionReplay"),(migration,"smart_assertion_replays"),(api,'/fhir/.well-known/smart-configuration'),(api,'"private_key_jwt"'),(api,'"RS384","ES384"'),(api,'"d","p","q","dp","dq","qi","oth"'),(api,"SmartAssertionReplay"),(api,'/oauth2/default/introspect'),(api,'/oauth2/default/revoke'),(security,"SMART Backend Services tokens are restricted to FHIR"),(security,'target in {"*",resource}'),(fhir,"SMART-on-FHIR"),(frontend,"Interactive public app"),(tests,"private-material"),(tests,"one-time-jti"))
for content,token in checks:assert token in content,f"SMART Backend Services contract missing: {token}"
interactive_checks=((models,"class SmartAuthorizationCode"),(models,"class SmartLaunchContext"),(interactive_migration,"smart_authorization_requests"),(api,'"authorization_code"'),(api,'"S256"'),(api,'"launch-ehr"'),(api,"encode_id_token"),(security,"smart_patient_access"),(consent,"Allow access"),(interactive_tests,"test_patient_portal_launch_issues_patient_identity"),(interactive_tests,"invalid_grant"))
for content,token in interactive_checks:assert token in content,f"SMART interactive contract missing: {token}"
assert "Base.metadata" not in auth_migration,"Historical auth migration must remain independent of current ORM metadata"
print("SMART App Launch contract verified")
