import { FormEvent, useEffect, useState } from "react";
import type { ApiRequest } from "../../api/client";
import { uiCopy, type UiLanguage } from "../../i18n";

type MfaStatus={enabled:boolean;method?:string;confirmed_at?:string;recovery_codes_remaining:number};
type Enrollment={secret:string;provisioning_uri:string};

export function SecurityWorkspace({api,language="es"}:{api:ApiRequest;language?:UiLanguage}){
  const [status,setStatus]=useState<MfaStatus|null>(null); const [enrollment,setEnrollment]=useState<Enrollment|null>(null); const [recoveryCodes,setRecoveryCodes]=useState<string[]>([]); const [error,setError]=useState("");
  const t=(spanish:string,english:string)=>uiCopy(language,spanish,english);
  async function load(){setStatus(await api<MfaStatus>("/api/v1/auth/mfa"));}
  useEffect(()=>{void load();},[]);
  async function enroll(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");const form=event.currentTarget,data=new FormData(form);try{setEnrollment(await api<Enrollment>("/api/v1/auth/mfa/enroll",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:data.get("password")})}));form.reset();}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo iniciar MFA");}}
  async function confirm(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);try{const result=await api<{recovery_codes:string[]}>("/api/v1/auth/mfa/confirm",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code:data.get("code")})});setRecoveryCodes(result.recovery_codes);setEnrollment(null);form.reset();await load();}catch(reason){setError(reason instanceof Error?reason.message:"Código inválido");}}
  async function disable(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);try{await api("/api/v1/auth/mfa",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:data.get("password"),code:data.get("code")})});form.reset();setRecoveryCodes([]);await load();}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo desactivar MFA");}}
  return <section className="card security-workspace"><p className="eyebrow">{t("SEGURIDAD DE LA CUENTA","ACCOUNT SECURITY")}</p><h2>{t("Autenticación multifactor","Multifactor authentication")}</h2>{error&&<p className="error">{error}</p>}{!status?<p>{t("Cargando…","Loading…")}</p>:status.enabled?<><p>{t("MFA mediante aplicación autenticadora está activo. Códigos de recuperación restantes:","Authenticator-app MFA is active. Recovery codes remaining:")} <strong>{status.recovery_codes_remaining}</strong>.</p><form className="quick-add" onSubmit={disable}><h3>{t("Desactivar MFA","Disable MFA")}</h3><input name="password" type="password" placeholder={t("Contraseña actual","Current password")} required/><input name="code" placeholder={t("Código TOTP o de recuperación","TOTP or recovery code")} required/><button>{t("Desactivar","Disable")}</button></form></>:enrollment?<><p>{t("Agrega esta cuenta a una aplicación TOTP usando el URI o la clave manual. Después confirma un código actual.","Add this account to a TOTP app using the URI or manual key, then confirm a current code.")}</p><code className="secret-value">{enrollment.secret}</code><details><summary>{t("Mostrar URI de configuración","Show setup URI")}</summary><code>{enrollment.provisioning_uri}</code></details><form className="quick-add" onSubmit={confirm}><input name="code" inputMode="numeric" placeholder={t("Código de 6 dígitos","6-digit code")} required/><button>{t("Confirmar MFA","Confirm MFA")}</button></form></>:<form className="quick-add" onSubmit={enroll}><p>{t("MFA añade un segundo factor al inicio de sesión. Se solicitará nuevamente tu contraseña para comenzar.","MFA adds a second factor at sign-in. Your password will be requested again to begin.")}</p><input name="password" type="password" placeholder={t("Contraseña actual","Current password")} required/><button>{t("Configurar aplicación TOTP","Set up TOTP app")}</button></form>}{recoveryCodes.length>0&&<section className="recovery-codes"><h3>{t("Guarda estos códigos de recuperación","Save these recovery codes")}</h3><p>{t("Se muestran una sola vez. Cada código sólo puede utilizarse una vez.","They are shown once. Each code can be used only once.")}</p><ul>{recoveryCodes.map(code=><li key={code}><code>{code}</code></li>)}</ul></section>}</section>;
}
