import { FormEvent, useEffect, useState } from "react";
import type { ApiRequest } from "../../api/client";

type MfaStatus={enabled:boolean;method?:string;confirmed_at?:string;recovery_codes_remaining:number};
type Enrollment={secret:string;provisioning_uri:string};

export function SecurityWorkspace({api}:{api:ApiRequest}){
  const [status,setStatus]=useState<MfaStatus|null>(null); const [enrollment,setEnrollment]=useState<Enrollment|null>(null); const [recoveryCodes,setRecoveryCodes]=useState<string[]>([]); const [error,setError]=useState("");
  async function load(){setStatus(await api<MfaStatus>("/api/v1/auth/mfa"));}
  useEffect(()=>{void load();},[]);
  async function enroll(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");const form=event.currentTarget,data=new FormData(form);try{setEnrollment(await api<Enrollment>("/api/v1/auth/mfa/enroll",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:data.get("password")})}));form.reset();}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo iniciar MFA");}}
  async function confirm(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);try{const result=await api<{recovery_codes:string[]}>("/api/v1/auth/mfa/confirm",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code:data.get("code")})});setRecoveryCodes(result.recovery_codes);setEnrollment(null);form.reset();await load();}catch(reason){setError(reason instanceof Error?reason.message:"Código inválido");}}
  async function disable(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);try{await api("/api/v1/auth/mfa",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:data.get("password"),code:data.get("code")})});form.reset();setRecoveryCodes([]);await load();}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo desactivar MFA");}}
  return <section className="card security-workspace"><p className="eyebrow">SEGURIDAD DE LA CUENTA</p><h2>Autenticación multifactor</h2>{error&&<p className="error">{error}</p>}{!status?<p>Cargando…</p>:status.enabled?<><p>MFA mediante aplicación autenticadora está activo. Códigos de recuperación restantes: <strong>{status.recovery_codes_remaining}</strong>.</p><form className="quick-add" onSubmit={disable}><h3>Desactivar MFA</h3><input name="password" type="password" placeholder="Contraseña actual" required/><input name="code" placeholder="Código TOTP o de recuperación" required/><button>Desactivar</button></form></>:enrollment?<><p>Agrega esta cuenta a una aplicación TOTP usando el URI o la clave manual. Después confirma un código actual.</p><code className="secret-value">{enrollment.secret}</code><details><summary>Mostrar URI de configuración</summary><code>{enrollment.provisioning_uri}</code></details><form className="quick-add" onSubmit={confirm}><input name="code" inputMode="numeric" placeholder="Código de 6 dígitos" required/><button>Confirmar MFA</button></form></>:<form className="quick-add" onSubmit={enroll}><p>MFA añade un segundo factor al inicio de sesión. Se solicitará nuevamente tu contraseña para comenzar.</p><input name="password" type="password" placeholder="Contraseña actual" required/><button>Configurar aplicación TOTP</button></form>}{recoveryCodes.length>0&&<section className="recovery-codes"><h3>Guarda estos códigos de recuperación</h3><p>Se muestran una sola vez. Cada código sólo puede utilizarse una vez.</p><ul>{recoveryCodes.map(code=><li key={code}><code>{code}</code></li>)}</ul></section>}</section>;
}
