import { FormEvent, useEffect, useRef, useState } from "react";
import { createApiClient } from "../../api/client";
import type { MessageThread } from "./CommunicationWorkspace";
import { PortalRecords } from "./PortalRecords";

export function PortalApp({baseUrl}:{baseUrl:string}) {
  const [token,setToken]=useState(""); const [authReady,setAuthReady]=useState(false); const [resetRequired,setResetRequired]=useState(false); const [threads,setThreads]=useState<MessageThread[]>([]); const [selected,setSelected]=useState<MessageThread|null>(null); const [error,setError]=useState(""); const refreshInFlight=useRef<Promise<string|null>|null>(null);
  function refreshAccessToken(){if(!refreshInFlight.current)refreshInFlight.current=fetch(`${baseUrl}/api/v1/portal/auth/refresh`,{method:"POST",credentials:"include"}).then(async response=>{if(!response.ok)return null;const result=await response.json();setResetRequired(result.force_password_reset);setToken(result.access_token);return result.access_token as string;}).finally(()=>{refreshInFlight.current=null;});return refreshInFlight.current;}
  const api=createApiClient({baseUrl,getToken:()=>token,refreshAccessToken,onUnauthorized:()=>setToken("")});
  async function load(){if(token&&!resetRequired)setThreads(await api<MessageThread[]>("/api/v1/portal/messages"));}
  useEffect(()=>{if(token){setAuthReady(true);return;}void refreshAccessToken().finally(()=>setAuthReady(true));},[]);
  useEffect(()=>{void load();},[token,resetRequired]);
  async function login(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");const form=new FormData(event.currentTarget);try{const response=await fetch(`${baseUrl}/api/v1/portal/auth/token`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:form.get("username"),password:form.get("password")})});if(!response.ok)throw new Error();const result=await response.json();setResetRequired(result.force_password_reset);setToken(result.access_token);}catch{setError("Usuario o contraseña inválidos");}}
  async function logout(){try{await api("/api/v1/portal/auth/logout",{method:"POST"});}finally{setToken("");}}
  async function resetPassword(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);try{await api("/api/v1/portal/password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({new_password:form.get("password")})});setResetRequired(false);}catch(reason){setError(reason instanceof Error?reason.message:"Password could not be changed");}}
  async function open(uuid:string){setSelected(await api<MessageThread>(`/api/v1/portal/messages/${uuid}`));}
  async function send(event:FormEvent<HTMLFormElement>){event.preventDefault();const element=event.currentTarget;const form=new FormData(element);const thread=await api<MessageThread>("/api/v1/portal/messages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({subject:form.get("subject"),body:form.get("body")})});element.reset();setSelected(thread);await load();}
  async function reply(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;const element=event.currentTarget;const form=new FormData(element);setSelected(await api<MessageThread>(`/api/v1/portal/messages/${selected.uuid}/replies`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({body:form.get("body")})}));element.reset();await load();}
  if(!authReady)return <main className="login"><p>Checking session…</p></main>;
  if(!token)return <main className="login"><form onSubmit={login}><p className="eyebrow">OPENRM PATIENT PORTAL</p><h1>Secure messages</h1><label>Username<input name="username" required/></label><label>Password<input name="password" type="password" required minLength={8}/></label>{error&&<p className="error">{error}</p>}<button>Sign in</button></form></main>;
  if(resetRequired)return <main className="login"><form onSubmit={resetPassword}><p className="eyebrow">OPENRM PATIENT PORTAL</p><h1>Choose a new password</h1><p>Your temporary password must be replaced before accessing health information.</p><label>New password<input name="password" type="password" required minLength={12}/></label>{error&&<p className="error">{error}</p>}<button>Save password</button></form></main>;
  return <main className="portal-shell"><header><div><p className="eyebrow">PATIENT PORTAL</p><h1>My health and care</h1></div><button onClick={()=>void logout()}>Sign out</button></header><PortalRecords api={api}/><h2>Secure messages</h2><div className="communications-grid"><section className="card communications-list"><form className="communications-compose" onSubmit={send}><h2>New message</h2><input name="subject" placeholder="Subject" required/><textarea name="body" placeholder="Message" required/><button>Send securely</button></form>{threads.map(thread=><button className="thread-row" key={thread.uuid} onClick={()=>void open(thread.uuid)}><strong>{thread.subject}</strong><span>{thread.status}</span></button>)}</section><section className="card thread-detail">{selected?<><h2>{selected.subject}</h2><div className="message-stack">{selected.messages.map(message=><article className={`secure-message ${message.sender_kind}`} key={message.uuid}><strong>{message.sender_kind==="patient"?"You":"Care team"}</strong><p>{message.body}</p><small>{new Date(message.created_at).toLocaleString()}</small></article>)}</div>{selected.status==="open"&&<form className="reply-form" onSubmit={reply}><textarea name="body" aria-label="Reply" required/><button>Reply</button></form>}</>:<div className="empty">Select a conversation.</div>}</section></div></main>;
}
