import { FormEvent, useEffect, useState } from "react";
import type { ApiRequest } from "../../api/client";

type MfaStatus={enabled:boolean;method?:string;confirmed_at?:string;recovery_codes_remaining:number};
type Enrollment={secret:string;provisioning_uri:string};

export function PortalSecurity({api}:{api:ApiRequest}){
  const [status,setStatus]=useState<MfaStatus|null>(null); const [enrollment,setEnrollment]=useState<Enrollment|null>(null); const [recoveryCodes,setRecoveryCodes]=useState<string[]>([]); const [error,setError]=useState("");
  async function load(){setStatus(await api<MfaStatus>("/api/v1/portal/mfa"));}
  useEffect(()=>{void load();},[]);
  async function enroll(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);setError("");try{setEnrollment(await api<Enrollment>("/api/v1/portal/mfa/enroll",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:data.get("password")})}));form.reset();}catch(reason){setError(reason instanceof Error?reason.message:"MFA enrollment could not be started");}}
  async function confirm(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);try{const result=await api<{recovery_codes:string[]}>("/api/v1/portal/mfa/confirm",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code:data.get("code")})});setRecoveryCodes(result.recovery_codes);setEnrollment(null);form.reset();await load();}catch(reason){setError(reason instanceof Error?reason.message:"The authenticator code is invalid");}}
  async function disable(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);try{await api("/api/v1/portal/mfa",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:data.get("password"),code:data.get("code")})});form.reset();setRecoveryCodes([]);await load();}catch(reason){setError(reason instanceof Error?reason.message:"MFA could not be disabled");}}
  return <section className="card security-workspace portal-security"><p className="eyebrow">ACCOUNT SECURITY</p><h2>Multi-factor authentication</h2>{error&&<p className="error">{error}</p>}{!status?<p>Loading…</p>:status.enabled?<><p>Authenticator-app MFA is active. Recovery codes remaining: <strong>{status.recovery_codes_remaining}</strong>.</p><form className="quick-add" onSubmit={disable}><h3>Disable MFA</h3><input name="password" type="password" placeholder="Current password" required/><input name="code" placeholder="Authenticator or recovery code" required/><button>Disable MFA</button></form></>:enrollment?<><p>Add this account to a TOTP authenticator, then enter a current code.</p><code className="secret-value">{enrollment.secret}</code><details><summary>Show provisioning URI</summary><code>{enrollment.provisioning_uri}</code></details><form className="quick-add" onSubmit={confirm}><input name="code" inputMode="numeric" placeholder="6-digit code" required/><button>Confirm MFA</button></form></>:<form className="quick-add" onSubmit={enroll}><p>MFA requires a second factor whenever you sign in.</p><input name="password" type="password" placeholder="Current password" required/><button>Set up authenticator app</button></form>}{recoveryCodes.length>0&&<section className="recovery-codes"><h3>Save these recovery codes</h3><p>They are shown once. Each code can be used only once.</p><ul>{recoveryCodes.map(code=><li key={code}><code>{code}</code></li>)}</ul></section>}</section>;
}
