import { FormEvent, useEffect, useRef, useState } from "react";
import { createApiClient } from "../../api/client";
import type { MessageThread } from "./CommunicationWorkspace";
import { PortalRecords } from "./PortalRecords";
import { PortalPasswordRecovery } from "./PortalPasswordRecovery";

type PortalContext = {patient_uuid:string;patient_name:string;relationship_code:string;scopes:string[];is_self:boolean};

export function PortalApp({baseUrl}:{baseUrl:string}) {
  const [token,setToken]=useState(""); const [authReady,setAuthReady]=useState(false); const [resetRequired,setResetRequired]=useState(false); const [challenge,setChallenge]=useState(""); const [contexts,setContexts]=useState<PortalContext[]>([]); const [patientUuid,setPatientUuid]=useState(""); const [threads,setThreads]=useState<MessageThread[]>([]); const [selected,setSelected]=useState<MessageThread|null>(null); const [error,setError]=useState(""); const refreshInFlight=useRef<Promise<string|null>|null>(null);
  function refreshAccessToken(){if(!refreshInFlight.current)refreshInFlight.current=fetch(`${baseUrl}/api/v1/portal/auth/refresh`,{method:"POST",credentials:"include"}).then(async response=>{if(!response.ok)return null;const result=await response.json();setResetRequired(result.force_password_reset);setToken(result.access_token);return result.access_token as string;}).finally(()=>{refreshInFlight.current=null;});return refreshInFlight.current;}
  const api=createApiClient({baseUrl,getToken:()=>token,refreshAccessToken,onUnauthorized:()=>setToken("")});
  const context=contexts.find(item=>item.patient_uuid===patientUuid);
  const contextHeaders=patientUuid?{"X-Portal-Patient":patientUuid}:undefined;
  async function loadContexts(){const available=await api<PortalContext[]>("/api/v1/portal/contexts");setContexts(available);setPatientUuid(current=>available.some(item=>item.patient_uuid===current)?current:(available.find(item=>item.is_self)||available[0])?.patient_uuid||"");}
  async function load(){if(token&&!resetRequired&&patientUuid&&context?.scopes.includes("messages"))setThreads(await api<MessageThread[]>("/api/v1/portal/messages",{headers:contextHeaders}));else setThreads([]);}
  useEffect(()=>{if(token){setAuthReady(true);return;}void refreshAccessToken().finally(()=>setAuthReady(true));},[]);
  useEffect(()=>{if(token&&!resetRequired)void loadContexts();else{setContexts([]);setPatientUuid("");}},[token,resetRequired]);
  useEffect(()=>{setSelected(null);void load();},[token,resetRequired,patientUuid,context?.scopes.join(",")]);
  async function login(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");const form=new FormData(event.currentTarget);try{const response=await fetch(`${baseUrl}/api/v1/portal/auth/token`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:form.get("username"),password:form.get("password")})});if(!response.ok)throw new Error();const result=await response.json();setResetRequired(result.force_password_reset);if(result.mfa_required)setChallenge(result.challenge_token);else setToken(result.access_token);}catch{setError("Invalid username or password");}}
  async function verifyMfa(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");const form=new FormData(event.currentTarget);const response=await fetch(`${baseUrl}/api/v1/portal/auth/mfa/challenge`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({challenge_token:challenge,code:form.get("code")})});if(!response.ok){setError("Invalid or expired security code");return;}const result=await response.json();setResetRequired(result.force_password_reset);setChallenge("");setToken(result.access_token);}
  async function logout(){try{await api("/api/v1/portal/auth/logout",{method:"POST"});}finally{setToken("");}}
  async function resetPassword(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);try{await api("/api/v1/portal/password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({new_password:form.get("password")})});setResetRequired(false);}catch(reason){setError(reason instanceof Error?reason.message:"Password could not be changed");}}
  async function open(uuid:string){setSelected(await api<MessageThread>(`/api/v1/portal/messages/${uuid}`,{headers:contextHeaders}));}
  async function send(event:FormEvent<HTMLFormElement>){event.preventDefault();const element=event.currentTarget;const form=new FormData(element);const thread=await api<MessageThread>("/api/v1/portal/messages",{method:"POST",headers:{"Content-Type":"application/json",...contextHeaders},body:JSON.stringify({subject:form.get("subject"),body:form.get("body")})});element.reset();setSelected(thread);await load();}
  async function reply(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;const element=event.currentTarget;const form=new FormData(element);setSelected(await api<MessageThread>(`/api/v1/portal/messages/${selected.uuid}/replies`,{method:"POST",headers:{"Content-Type":"application/json",...contextHeaders},body:JSON.stringify({body:form.get("body")})}));element.reset();await load();}
  if(window.location.pathname.startsWith("/portal/reset-password"))return <PortalPasswordRecovery baseUrl={baseUrl}/>;
  if(!authReady)return <main className="login"><p>Checking session…</p></main>;
  if(challenge)return <main className="login"><form onSubmit={verifyMfa}><p className="eyebrow">OPENRM PATIENT PORTAL</p><h1>Security code</h1><p>Enter a current authenticator code or a recovery code.</p><label>Code<input name="code" autoComplete="one-time-code" autoFocus required/></label>{error&&<p className="error">{error}</p>}<button>Verify</button><button className="secondary" type="button" onClick={()=>{setChallenge("");setError("");}}>Cancel</button></form></main>;
  if(!token)return <main className="login"><form onSubmit={login}><p className="eyebrow">OPENRM PATIENT PORTAL</p><h1>My health and care</h1><label>Username<input name="username" required/></label><label>Password<input name="password" type="password" required minLength={8}/></label>{error&&<p className="error">{error}</p>}<button>Sign in</button><a className="auth-link" href="/portal/reset-password">Forgot your password?</a></form></main>;
  if(resetRequired)return <main className="login"><form onSubmit={resetPassword}><p className="eyebrow">OPENRM PATIENT PORTAL</p><h1>Choose a new password</h1><p>Your temporary password must be replaced before accessing health information.</p><label>New password<input name="password" type="password" required minLength={12}/></label>{error&&<p className="error">{error}</p>}<button>Save password</button></form></main>;
  return <main className="portal-shell"><header><div><p className="eyebrow">PATIENT PORTAL</p><h1>My health and care</h1></div><button onClick={()=>void logout()}>Sign out</button></header>{contexts.length?<section className="card portal-context"><label>Viewing records for<select aria-label="Patient context" value={patientUuid} onChange={event=>setPatientUuid(event.target.value)}>{contexts.map(item=><option value={item.patient_uuid} key={item.patient_uuid}>{item.patient_name}{item.is_self?" (me)":` · ${item.relationship_code}`}</option>)}</select></label>{context&&!context.is_self&&<p>You are viewing this record as an authorized {context.relationship_code}. Available areas: {context.scopes.join(", ")}.</p>}</section>:<section className="card portal-context"><h2>No patient access</h2><p>This identity does not currently have an active patient access grant. Contact the practice if you believe this is incorrect.</p></section>}{context&&<><PortalRecords api={api} patientUuid={patientUuid} scopes={context.scopes}/>{context.scopes.includes("messages")&&<><h2>Secure messages</h2><div className="communications-grid"><section className="card communications-list"><form className="communications-compose" onSubmit={send}><h2>New message</h2><input name="subject" placeholder="Subject" required/><textarea name="body" placeholder="Message" required/><button>Send securely</button></form>{threads.map(thread=><button className="thread-row" key={thread.uuid} onClick={()=>void open(thread.uuid)}><strong>{thread.subject}</strong><span>{thread.status}</span></button>)}</section><section className="card thread-detail">{selected?<><h2>{selected.subject}</h2><div className="message-stack">{selected.messages.map(message=><article className={`secure-message ${message.sender_kind}`} key={message.uuid}><strong>{message.sender_kind==="patient"?"You":"Care team"}</strong><p>{message.body}</p><small>{new Date(message.created_at).toLocaleString()}</small></article>)}</div>{selected.status==="open"&&<form className="reply-form" onSubmit={reply}><textarea name="body" aria-label="Reply" required/><button>Reply</button></form>}</>:<div className="empty">Select a conversation.</div>}</section></div></>}</>}</main>;
}
