import { FormEvent, useEffect, useState } from "react";
import type { ApiRequest } from "../../api/client";
import type { Patient } from "../patients/types";

type Representative={uuid:string;username:string;display_name?:string};
type Grant={uuid:string;patient_uuid:string;representative_name:string;relationship_code:string;scopes:string[];revoked_at?:string};
const SCOPES=["appointments","records","documents","forms","messages","billing"];

export function PortalAccessManager({api,patients}:{api:ApiRequest;patients:Patient[]}){
  const [representatives,setRepresentatives]=useState<Representative[]>([]); const [grants,setGrants]=useState<Grant[]>([]); const [patientUuid,setPatientUuid]=useState(""); const [notice,setNotice]=useState("");
  async function loadRepresentatives(){setRepresentatives(await api<Representative[]>("/api/v1/portal-representatives"));}
  async function loadGrants(value:string){setPatientUuid(value);setGrants(value?await api<Grant[]>(`/api/v1/patients/${value}/portal-access-grants`):[]);}
  useEffect(()=>{void loadRepresentatives();},[]);
  async function createRepresentative(event:FormEvent<HTMLFormElement>){event.preventDefault();const element=event.currentTarget;const form=new FormData(element);await api("/api/v1/portal-representatives",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:form.get("username"),email:form.get("email"),display_name:form.get("display_name"),temporary_password:form.get("temporary_password")})});element.reset();setNotice("Representative identity created. Share the temporary password through an approved channel.");await loadRepresentatives();}
  async function createGrant(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const scopes=SCOPES.filter(scope=>form.get(scope));const target=String(form.get("patient_uuid"));await api(`/api/v1/patients/${target}/portal-access-grants`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({representative_username:form.get("representative_username"),relationship_code:form.get("relationship_code"),consent_basis:form.get("consent_basis"),evidence_reference:form.get("evidence_reference")||null,scopes})});setNotice("Patient access granted with the selected scopes.");await loadGrants(target);}
  async function revoke(grant:Grant){await api(`/api/v1/patients/${grant.patient_uuid}/portal-access-grants/${grant.uuid}/revoke`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({reason:"Access revoked by authorized staff"})});setNotice("Access revoked immediately.");await loadGrants(grant.patient_uuid);}
  return <section className="card portal-access-manager"><h2>Authorized portal access</h2><p>Create a distinct identity for a caregiver or legal representative, then grant only the patient areas supported by documented consent or authority.</p>{notice&&<p className="portal-notice">{notice}</p>}<div className="portal-access-grid"><form onSubmit={createRepresentative}><h3>Representative identity</h3><input name="display_name" aria-label="Representative name" placeholder="Full name" required/><input name="email" type="email" placeholder="Email" required/><input name="username" placeholder="Portal username" required minLength={3}/><input name="temporary_password" type="password" placeholder="Temporary password" required minLength={12}/><button>Create identity</button></form><form onSubmit={createGrant}><h3>Patient grant</h3><select name="patient_uuid" aria-label="Grant patient" required onChange={event=>void loadGrants(event.target.value)}><option value="">Select patient</option>{patients.map(patient=><option value={patient.uuid} key={patient.uuid}>{patient.last_name}, {patient.first_name}</option>)}</select><select name="representative_username" aria-label="Representative" required><option value="">Select representative</option>{representatives.map(item=><option value={item.username} key={item.uuid}>{item.display_name||item.username}</option>)}</select><input name="relationship_code" placeholder="Relationship (for example, guardian)" required/><select name="consent_basis" aria-label="Authority basis" required><option value="patient-consent">Patient consent</option><option value="legal-guardian">Legal guardian</option><option value="parental-authority">Parental authority</option><option value="court-order">Court order</option><option value="power-of-attorney">Power of attorney</option></select><input name="evidence_reference" placeholder="Consent or evidence reference"/><fieldset><legend>Allowed areas</legend>{SCOPES.map(scope=><label key={scope}><input type="checkbox" name={scope} defaultChecked/>{scope}</label>)}</fieldset><button>Grant access</button></form></div>{patientUuid&&<div><h3>Grant history</h3>{grants.map(grant=><article key={grant.uuid}><strong>{grant.representative_name}</strong><p>{grant.relationship_code} · {grant.scopes.join(", ")}</p>{grant.revoked_at?<small>Revoked</small>:<button className="secondary" onClick={()=>void revoke(grant)}>Revoke access</button>}</article>)}{!grants.length&&<p>No grants recorded for this patient.</p>}</div>}</section>;
}
