import { FormEvent, useEffect, useState } from "react";
import type { ApiRequest } from "../../api/client";

type Question = {id:string; text:string; type?:"integer"|"boolean"|"string"|"choice"; min?:number; max?:number; options?:string[]};
type Assignment = {uuid:string; title:string; questions:Question[]; instructions?:string; status:string; due_at?:string};
type Notice = {uuid:string; event_type:string; title:string; body:string; created_at:string; read_at?:string};
type Preferences = {email_enabled:boolean; sms_enabled:boolean; in_app_enabled:boolean; message_events:boolean; appointment_events:boolean; result_events:boolean; questionnaire_events:boolean; timezone_name:string; quiet_hours_start?:string; quiet_hours_end?:string};

export function PortalEngagement({api,patientUuid,scopes}:{api:ApiRequest;patientUuid:string;scopes:string[]}) {
  const headers={"X-Portal-Patient":patientUuid};
  const [assignments,setAssignments]=useState<Assignment[]>([]); const [notices,setNotices]=useState<Notice[]>([]); const [preferences,setPreferences]=useState<Preferences|null>(null); const [error,setError]=useState("");
  async function load(){try{if(scopes.includes("questionnaires"))setAssignments(await api<Assignment[]>("/api/v1/portal/questionnaires",{headers}));if(scopes.includes("notifications")){setNotices(await api<Notice[]>("/api/v1/portal/notifications",{headers}));setPreferences(await api<Preferences>("/api/v1/portal/notification-preferences",{headers}));}}catch(reason){setError(reason instanceof Error?reason.message:"Portal information could not be loaded");}}
  useEffect(()=>{void load();},[patientUuid,scopes.join(",")]);
  async function submitQuestionnaire(event:FormEvent<HTMLFormElement>,assignment:Assignment){event.preventDefault();const form=new FormData(event.currentTarget);const answers=Object.fromEntries(assignment.questions.map(question=>{const raw=form.get(question.id);const kind=question.type||"integer";return [question.id,kind==="integer"?Number(raw):kind==="boolean"?raw==="true":String(raw||"")];}));await api(`/api/v1/portal/questionnaires/${assignment.uuid}/responses`,{method:"POST",headers:{"Content-Type":"application/json",...headers},body:JSON.stringify({answers})});await load();}
  async function savePreferences(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!preferences)return;const form=new FormData(event.currentTarget);const toggles=["email_enabled","sms_enabled","in_app_enabled","message_events","appointment_events","result_events","questionnaire_events"];const body={...preferences,...Object.fromEntries(toggles.map(key=>[key,form.has(key)])),timezone_name:String(form.get("timezone_name")||"UTC")};setPreferences(await api<Preferences>("/api/v1/portal/notification-preferences",{method:"PUT",headers:{"Content-Type":"application/json",...headers},body:JSON.stringify(body)}));}
  async function markRead(uuid:string){await api(`/api/v1/portal/notifications/${uuid}/read`,{method:"POST",headers});await load();}
  return <>{error&&<p className="error">{error}</p>}{scopes.includes("questionnaires")&&<section className="card" id="questionnaires"><h2>Questionnaires</h2>{assignments.map(item=><article key={item.uuid} className="portal-record"><h3>{item.title}</h3>{item.instructions&&<p>{item.instructions}</p>}{item.status==="assigned"?<form onSubmit={event=>void submitQuestionnaire(event,item)}>{item.questions.map(question=><label key={question.id}>{question.text}{question.type==="boolean"?<select name={question.id} required><option value="">Choose</option><option value="true">Yes</option><option value="false">No</option></select>:question.type==="choice"?<select name={question.id} required><option value="">Choose</option>{question.options?.map(option=><option key={option}>{option}</option>)}</select>:<input name={question.id} type={!question.type||question.type==="integer"?"number":"text"} min={question.min} max={question.max} required/>}</label>)}<button>Submit questionnaire</button></form>:<p>Completed</p>}</article>)}{!assignments.length&&<p className="empty">No questionnaires are waiting for you.</p>}</section>}{scopes.includes("notifications")&&<><section className="card" id="notifications"><h2>Notifications</h2>{notices.map(item=><article className="portal-record" key={item.uuid}><h3>{item.title}</h3><p>{item.body}</p><small>{new Date(item.created_at).toLocaleString()}</small>{!item.read_at&&<button className="secondary" onClick={()=>void markRead(item.uuid)}>Mark as read</button>}</article>)}{!notices.length&&<p className="empty">No notifications.</p>}</section>{preferences&&<section className="card"><form onSubmit={savePreferences}><h2>Notification preferences</h2>{[["in_app_enabled","In-app"],["email_enabled","Email"],["sms_enabled","SMS"],["message_events","Messages"],["appointment_events","Appointments"],["result_events","Results"],["questionnaire_events","Questionnaires"]].map(([name,label])=><label key={name}><input type="checkbox" name={name} defaultChecked={Boolean(preferences[name as keyof Preferences])}/>{label}</label>)}<label>Time zone<input name="timezone_name" defaultValue={preferences.timezone_name}/></label><button>Save preferences</button></form></section>}</>}</>;
}
