import { FormEvent, useEffect, useState } from "react";
import type { ApiRequest } from "../../api/client";
import type { Patient } from "../patients/types";

type User={uuid:string;email:string;role:string}; type Questionnaire={uuid:string;title:string};
type Thread={uuid:string;subject:string;status:string;participants:{uuid:string;email:string}[];messages:{uuid:string;sender_name:string;body:string}[]};

export function StaffEngagement({api,patients}:{api:ApiRequest;patients:Patient[]}){
  const [users,setUsers]=useState<User[]>([]);const [questionnaires,setQuestionnaires]=useState<Questionnaire[]>([]);const [threads,setThreads]=useState<Thread[]>([]);const [selected,setSelected]=useState<Thread|null>(null);const [message,setMessage]=useState("");
  async function load(){try{const [directory,forms,mail]=await Promise.all([api<User[]>("/api/v1/staff-directory"),api<Questionnaire[]>("/api/v1/questionnaires"),api<Thread[]>("/api/v1/staff-message-threads")]);setUsers(directory);setQuestionnaires(forms);setThreads(mail);}catch(reason){setMessage(reason instanceof Error?reason.message:"Engagement tools could not be loaded");}}
  useEffect(()=>{void load();},[]);
  async function assign(event:FormEvent<HTMLFormElement>){event.preventDefault();const element=event.currentTarget;const form=new FormData(element);await api(`/api/v1/patients/${form.get("patient_uuid")}/questionnaire-assignments`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({questionnaire_uuid:form.get("questionnaire_uuid"),instructions:form.get("instructions")||null})});element.reset();setMessage("Questionnaire assigned.");}
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const element=event.currentTarget;const form=new FormData(element);const thread=await api<Thread>("/api/v1/staff-message-threads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({subject:form.get("subject"),body:form.get("body"),participant_user_uuids:form.getAll("participants")})});element.reset();setSelected(thread);await load();}
  async function open(uuid:string){setSelected(await api<Thread>(`/api/v1/staff-message-threads/${uuid}`));}
  async function reply(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;const element=event.currentTarget;const form=new FormData(element);setSelected(await api<Thread>(`/api/v1/staff-message-threads/${selected.uuid}/replies`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({body:form.get("body")})}));element.reset();await load();}
  return <section className="staff-engagement communication-section">
    <div className="communication-section-heading"><div><p className="eyebrow">COORDINACIÓN CLÍNICA</p><h2>Equipo y cuestionarios</h2></div><p>Asigna actividades al paciente y mantén conversaciones internas separadas del portal.</p></div>
    <section className="card questionnaire-card"><form className="questionnaire-form" onSubmit={assign}><div><p className="eyebrow">SEGUIMIENTO</p><h3>Assign a portal questionnaire</h3></div><label>Paciente del cuestionario<select aria-label="Questionnaire patient" name="patient_uuid" required><option value="">Patient</option>{patients.map(item=><option key={item.uuid} value={item.uuid}>{item.last_name}, {item.first_name}</option>)}</select></label><label>Cuestionario<select aria-label="Questionnaire" name="questionnaire_uuid" required><option value="">Questionnaire</option>{questionnaires.map(item=><option key={item.uuid} value={item.uuid}>{item.title}</option>)}</select></label><label className="questionnaire-instructions">Instrucciones<textarea name="instructions" placeholder="Instructions (optional)"/></label><button>Assign</button>{message&&<p className="success questionnaire-notice">{message}</p>}</form></section>
    <div className="communications-grid staff-communications">
      <section className="card communications-list"><form className="communications-compose staff-compose" onSubmit={create}><h3>Staff group message</h3><label>Asunto<input name="subject" placeholder="Staff subject" required/></label><label>Mensaje<textarea name="body" placeholder="Message to staff" required/></label><label>Participantes<select name="participants" aria-label="Staff participants" multiple required>{users.map(item=><option key={item.uuid} value={item.uuid}>{item.email} · {item.role}</option>)}</select></label><button>Start conversation</button></form><div className="conversation-list-heading"><h3>Conversaciones internas</h3><span>{threads.length}</span></div>{threads.map(item=><button className="thread-row" key={item.uuid} onClick={()=>void open(item.uuid)}><strong>{item.subject}</strong><span>{item.status}</span></button>)}{!threads.length&&<p className="empty">No hay conversaciones internas.</p>}</section>
      <section className="card thread-detail">{selected?<><div className="thread-heading"><div><p className="eyebrow">CONVERSACIÓN INTERNA</p><h2>{selected.subject}</h2></div><span>{selected.status}</span></div><p className="thread-participants">{selected.participants.map(item=>item.email).join(", ")}</p><div className="message-stack">{selected.messages.map(item=><article className="secure-message" key={item.uuid}><strong>{item.sender_name}</strong><p>{item.body}</p></article>)}</div>{selected.status==="open"&&<form className="reply-form" onSubmit={reply}><label>Respuesta<textarea name="body" aria-label="Staff reply" required/></label><button>Reply</button></form>}</>:<div className="conversation-empty"><span aria-hidden="true">⌁</span><strong>Select a staff conversation.</strong><p>Los participantes y mensajes aparecerán aquí.</p></div>}</section>
    </div>
  </section>;
}
