import { FormEvent, useEffect, useState } from "react";
import type { ApiRequest } from "../../api/client";

type CatalogItem={key:string;title:string;category:string;permission:string;legacy_path:string;migrated:boolean};
type ReportRun={uuid:string;report_key:string;parameters:Record<string,unknown>;columns:string[];rows:Record<string,unknown>[];totals:Record<string,unknown>;row_count:number;checksum:string;created_at:string};

export function ReportWorkspace({api}:{api:ApiRequest}){
  const [catalog,setCatalog]=useState<CatalogItem[]>([]);
  const [selected,setSelected]=useState<CatalogItem|null>(null);
  const [run,setRun]=useState<ReportRun|null>(null);
  const [error,setError]=useState("");
  useEffect(()=>{api<CatalogItem[]>("/api/v1/reports").then(setCatalog).catch(reason=>setError(reason instanceof Error?reason.message:"Could not load reports"));},[]);

  async function execute(event:FormEvent<HTMLFormElement>){
    event.preventDefault();if(!selected)return;
    const data=new FormData(event.currentTarget);const value=(key:string)=>data.get(key)||null;
    const body={date_from:value("date_from"),date_to:value("date_to"),occurred_from:value("occurred_from"),occurred_to:value("occurred_to"),status:value("status"),warehouse_code:value("warehouse_code"),patient_uuid:value("patient_uuid"),facility_uuid:value("facility_uuid"),clinical_type:value("clinical_type"),age_from:value("age_from")?Number(value("age_from")):null,age_to:value("age_to")?Number(value("age_to")):null,gender:value("gender"),race:value("race"),ethnicity:value("ethnicity"),diagnosis:value("diagnosis"),drug_name:value("drug_name"),lab_result:value("lab_result"),service_code:value("service_code"),immunization:value("immunization"),communication:value("communication"),include_allergies:data.has("include_allergies"),include_problems:data.has("include_problems"),include_prescriptions:data.has("include_prescriptions"),include_ndc:data.has("include_ndc"),include_lab_results:data.has("include_lab_results"),include_communication:data.has("include_communication"),sort_patient_name:data.has("sort_patient_name"),sort_patient_age:data.has("sort_patient_age"),include_details:!data.has("summary_only"),only_with_failures:data.has("only_with_failures"),only_manually_blocked:data.has("only_manually_blocked"),only_auto_blocked:data.has("only_auto_blocked"),collection_category:value("collection_category"),age_by:value("age_by")||"service_date",age_columns:value("age_columns")?Number(value("age_columns")):3,age_increment_days:value("age_increment_days")?Number(value("age_increment_days")):30,as_of_date:value("as_of_date"),payer_legacy_id:value("payer_legacy_id")?Number(value("payer_legacy_id")):null,provider_legacy_id:value("provider_legacy_id")?Number(value("provider_legacy_id")):null,with_debt_only:data.has("with_debt_only"),include_zero_balances:data.has("include_zero_balances"),receipt_report_by:value("receipt_report_by")||"payer",use_invoice_date:data.has("use_invoice_date"),procedure_code:value("procedure_code"),payment_service:value("payment_service"),payment_ticket:value("payment_ticket"),payment_transaction_id:value("payment_transaction_id"),payment_action:value("payment_action"),parked_only:data.has("parked_only"),financial_reporting_only:data.has("financial_reporting_only"),reportable_code_ids:String(value("reportable_code_ids")||"").split(",").map(entry=>Number(entry.trim())).filter(entry=>Number.isInteger(entry)&&entry>0)};
    try{setRun(await api<ReportRun>(`/api/v1/reports/${selected.key}/runs`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}));setError("");}catch(reason){setError(reason instanceof Error?reason.message:"Could not run report");}
  }
  async function download(){if(!run||!api.raw)return setError("Authenticated export is unavailable");try{const response=await api.raw(`/api/v1/report-runs/${run.uuid}/export.csv`);const url=URL.createObjectURL(await response.blob());const link=document.createElement("a");link.href=url;link.download=`${run.report_key}.csv`;link.click();URL.revokeObjectURL(url);}catch(reason){setError(reason instanceof Error?reason.message:"Could not export report");}}
  async function downloadHl7(){if(!run||!api.raw)return setError("Authenticated export is unavailable");try{const response=await api.raw(`/api/v1/report-runs/${run.uuid}/export.hl7`);const url=URL.createObjectURL(await response.blob());const link=document.createElement("a");link.href=url;link.download="syndromic-surveillance.hl7";link.click();URL.revokeObjectURL(url);}catch(reason){setError(reason instanceof Error?reason.message:"Could not export HL7");}}
  const categories=[...new Set(catalog.map(item=>item.category))];
  return <section className="report-workspace">
    <section className="card report-catalog"><h2>Report catalog <span>{catalog.length}</span></h2>{categories.map(category=><div key={category}><h3>{category}</h3>{catalog.filter(item=>item.category===category).map(item=><button key={item.key} className={selected?.key===item.key?"report-item selected":"report-item"} onClick={()=>{setSelected(item);setRun(null);setError("");}}><span>{item.title}</span><small>{item.migrated?"Available":"Migration pending"}</small></button>)}</div>)}</section>
    <section className="card report-viewer">{selected?<><p className="eyebrow">{selected.category}</p><h2>{selected.title}</h2><small>{selected.legacy_path}</small>{selected.migrated?<form className="report-filters" onSubmit={execute}>
      <label>From<input name="date_from" type="date"/></label><label>To<input name="date_to" type="date"/></label><label>Status<input name="status"/></label><label>Warehouse<input name="warehouse_code"/></label>
      {selected.key==="chart_location_activity"&&<label>Patient UUID<input name="patient_uuid" required/></label>}
      {selected.key==="appt_encounter_report"&&<><label>Facility UUID<input name="facility_uuid"/></label><label><input name="summary_only" type="checkbox"/> Provider totals only</label></>}
      {selected.key==="collections_report"&&<CollectionFilters/>}
      {selected.key==="front_receipts_report"&&<><label>Facility UUID<input name="facility_uuid"/></label><label>Provider legacy ID<input name="provider_legacy_id" type="number" min="1"/></label></>}
      {selected.key==="receipts_by_method_report"&&<ReceiptMethodFilters/>}
      {selected.key==="payment_processing_report"&&<PaymentProcessingFilters/>}
      {selected.key==="prepayment_balance_report"&&<><label>Patient UUID<input name="patient_uuid"/></label><label><input name="parked_only" type="checkbox"/> Parked in global only</label></>}
      {selected.key==="svc_code_financial_report"&&<><label>Facility UUID<input name="facility_uuid"/></label><label>Provider legacy ID<input name="provider_legacy_id" type="number" min="1"/></label><label><input name="financial_reporting_only" type="checkbox"/> Important codes only</label></>}
      {selected.key==="rwt_2026_report"&&<p>Fixed ONC measurement period: April 1–September 30, 2026.</p>}
      {selected.key==="custom_report_range"&&<><label>Patient UUID<input name="patient_uuid"/></label><p>Select a required date range, then print the generated Superbill for signature.</p></>}
      {selected.key==="non_reported"&&<><label>Sending facility UUID<input name="facility_uuid" required/></label><label>Legacy reportable code IDs<input name="reportable_code_ids" placeholder="12, 34"/></label><label>Patient UUID<input name="patient_uuid"/></label></>}
      {selected.key==="pat_ledger"&&<><label>Patient UUID<input name="patient_uuid" required/></label><label>Facility UUID<input name="facility_uuid"/></label><label>Provider legacy ID<input name="provider_legacy_id" type="number" min="1"/></label></>}
      {selected.key==="clinical_reports"&&<ClinicalReportFilters/>}<button>Run report</button>
    </form>:<p className="pending-notice">This legacy report is inventoried and remains in the migration queue.</p>}{error&&<p className="error">{error}</p>}{run&&<><div className="report-meta"><strong>{run.row_count} rows</strong><span>Checksum {run.checksum.slice(0,12)}…</span><button onClick={()=>void download()}>Export CSV</button>{run.report_key==="custom_report_range"&&<button onClick={()=>window.print()}>Print Superbill</button>}{run.report_key==="non_reported"&&run.row_count>0&&<button onClick={()=>void downloadHl7()}>Export and mark HL7 sent</button>}</div>{run.report_key==="custom_report_range"?<SuperbillView rows={run.rows}/>:<div className="report-table"><table><thead><tr>{run.columns.map(column=><th key={column}>{column.replaceAll("_"," ")}</th>)}</tr></thead><tbody>{run.rows.map((row,index)=><tr key={index}>{run.columns.map(column=><td key={column}>{String(row[column]??"—")}</td>)}</tr>)}</tbody></table></div>}<div className="report-totals">{Object.entries(run.totals).filter(([,entry])=>typeof entry!=="object").map(([key,entry])=><span key={key}><strong>{String(entry)}</strong> {key.replaceAll("_"," ")}</span>)}</div></>}</>:<div className="empty">Select a report to inspect its migration status and parameters.</div>}</section>
  </section>;
}

function SuperbillView({rows}:{rows:Record<string,unknown>[]}){
  const groups=[...new Set(rows.map(row=>String(row.superbill_uuid)))];
  const shown=(value:unknown)=>value===null||value===undefined||value===""?"—":String(value);
  return <div className="superbill-list">{groups.map(uuid=>{const items=rows.filter(row=>String(row.superbill_uuid)===uuid);const row=items[0];return <article className="superbill" key={uuid}>
    <header><h2>{shown(row.billing_facility)}</h2><p>{shown(row.billing_facility_address)}</p><small>Encounter {shown(row.legacy_encounter_id)} · {shown(row.encounter_date)}</small></header>
    <section><h3>Patient Data</h3><dl><div><dt>Name</dt><dd>{shown([row.patient_fname,row.patient_mname,row.patient_lname].filter(Boolean).join(" "))}</dd></div><div><dt>Date of birth</dt><dd>{shown(row.patient_DOB)}</dd></div><div><dt>Sex</dt><dd>{shown(row.patient_sex)}</dd></div><div><dt>Address</dt><dd>{shown([row.patient_street,row.patient_city,row.patient_state,row.patient_postal_code].filter(Boolean).join(", "))}</dd></div><div><dt>Phone</dt><dd>{shown(row.patient_phone_home)}</dd></div><div><dt>Patient ID</dt><dd>{shown(row.legacy_patient_id)}</dd></div></dl></section>
    <section><h3>Insurance Data</h3><div className="superbill-coverages">{(["primary","secondary","tertiary"] as const).map(priority=><div key={priority}><strong>{priority}</strong><span>{shown(row[`${priority}_provider_name`])}</span><span>{shown(row[`${priority}_plan_name`])}</span><span>Policy {shown(row[`${priority}_policy_number`])}</span><span>Subscriber {shown([row[`${priority}_subscriber_fname`],row[`${priority}_subscriber_mname`],row[`${priority}_subscriber_lname`]].filter(Boolean).join(" "))}</span></div>)}</div></section>
    <section><h3>Billing Information</h3><table><thead><tr><th>Date</th><th>Provider</th><th>Code</th><th>Fee</th></tr></thead><tbody>{items.map((item,index)=><tr key={index}><td>{shown(item.charge_date)}</td><td>{shown(item.provider)}</td><td>{item.code?`${shown(item.code_type)}: ${shown(item.code)} ${shown(item.modifier)==="—"?"":shown(item.modifier)} — ${shown(item.code_text)}`:"—"}</td><td>{shown(item.fee)}</td></tr>)}</tbody><tfoot><tr><th colSpan={3}>Sub-total</th><td>{shown(row.encounter_subtotal)}</td></tr><tr><th colSpan={3}>Copay paid</th><td>{shown(row.copay_paid)}</td></tr><tr><th colSpan={3}>Total</th><td>{shown(row.encounter_total)}</td></tr></tfoot></table></section>
    <footer>Physician Signature: _______________________________________________</footer>
  </article>})}</div>;
}

function ClinicalReportFilters(){return <>
  <label>Patient UUID<input name="patient_uuid"/></label><label>Facility UUID<input name="facility_uuid"/></label><label>Age from<input name="age_from" type="number" min="0" max="150"/></label><label>Age to<input name="age_to" type="number" min="0" max="150"/></label><label>Gender<input name="gender"/></label><label>Race<input name="race"/></label><label>Ethnicity<input name="ethnicity"/></label>
  <label>Report option<select name="clinical_type"><option value="">Cohort only</option><option>Procedure</option><option>Medical History</option><option>Service Codes</option></select></label><label>Diagnosis<input name="diagnosis"/></label><label><input name="include_problems" type="checkbox"/> Problems</label><label><input name="include_allergies" type="checkbox"/> Allergies</label><label>Drug<input name="drug_name"/></label><label><input name="include_prescriptions" type="checkbox"/> Prescriptions</label><label>Lab result<input name="lab_result"/></label><label><input name="include_lab_results" type="checkbox"/> Lab results</label><label>Service code<input name="service_code"/></label><label>Immunization<input name="immunization"/></label>
  <label>Communication<select name="communication"><option value="">Any</option><option value="allow_sms">SMS</option><option value="allow_voice">Voice</option><option value="allow_mail">Mail</option><option value="allow_email">Email</option></select></label><label><input name="include_communication" type="checkbox"/> Any communication consent</label><label><input name="sort_patient_name" type="checkbox"/> Sort by name</label><label><input name="sort_patient_age" type="checkbox"/> Sort by age</label>
</>}

function CollectionFilters(){return <>
  <label>Category<select name="collection_category" defaultValue="Due Pt"><option>Due Pt</option><option>Due Ins</option><option>Ins Summary</option><option>All</option><option>Credits</option></select></label><label>Facility UUID<input name="facility_uuid"/></label><label>Provider legacy ID<input name="provider_legacy_id" type="number" min="1"/></label><label>Payer legacy ID<input name="payer_legacy_id" type="number" min="1"/></label><label>Age by<select name="age_by"><option value="service_date">Service date</option><option value="last_activity">Last activity</option></select></label><label>Age columns<input name="age_columns" type="number" min="0" max="49" defaultValue="3"/></label><label>Days per column<input name="age_increment_days" type="number" min="1" defaultValue="30"/></label><label>As of<input name="as_of_date" type="date"/></label><label><input name="with_debt_only" type="checkbox"/> Positive debt only</label><label><input name="include_zero_balances" type="checkbox"/> Include zero balances</label>
</>}

function ReceiptMethodFilters(){return <>
  <label>Report by<select name="receipt_report_by"><option value="payer">Payer</option><option value="payment_method">Payment method</option><option value="check_number">Check number</option></select></label><label>Facility UUID<input name="facility_uuid"/></label><label>Provider legacy ID<input name="provider_legacy_id" type="number" min="1"/></label><label>Procedure code<input name="procedure_code" placeholder="CPT4:99213"/></label><label><input name="use_invoice_date" type="checkbox"/> Use invoice date</label><label><input name="summary_only" type="checkbox"/> Summary only</label>
</>}

function PaymentProcessingFilters(){return <>
  <label>Patient UUID<input name="patient_uuid"/></label><label>From timestamp<input name="occurred_from" type="datetime-local"/></label><label>To timestamp<input name="occurred_to" type="datetime-local"/></label><label>Service<input name="payment_service" placeholder="sphere"/></label><label>Ticket<input name="payment_ticket"/></label><label>Transaction ID<input name="payment_transaction_id"/></label><label>Action<select name="payment_action"><option value="">All</option><option>Sale</option><option>credit</option><option>void</option></select></label>
</>}
