import { FormEvent, useEffect, useState } from "react";
import type { ApiRequest } from "../../api/client";

type CatalogItem={key:string;title:string;category:string;permission:string;legacy_path:string;migrated:boolean};
type ReportRun={uuid:string;report_key:string;parameters:Record<string,unknown>;columns:string[];rows:Record<string,unknown>[];totals:Record<string,unknown>;row_count:number;checksum:string;created_at:string};

export function ReportWorkspace({api}:{api:ApiRequest}){
  const [catalog,setCatalog]=useState<CatalogItem[]>([]);const [selected,setSelected]=useState<CatalogItem|null>(null);const [run,setRun]=useState<ReportRun|null>(null);const [error,setError]=useState("");
  useEffect(()=>{api<CatalogItem[]>("/api/v1/reports").then(setCatalog).catch(reason=>setError(reason instanceof Error?reason.message:"Could not load reports"));},[]);
  async function execute(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;const data=new FormData(event.currentTarget);try{setRun(await api<ReportRun>(`/api/v1/reports/${selected.key}/runs`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({date_from:data.get("date_from")||null,date_to:data.get("date_to")||null,status:data.get("status")||null,warehouse_code:data.get("warehouse_code")||null,patient_uuid:data.get("patient_uuid")||null})}));setError("");}catch(reason){setError(reason instanceof Error?reason.message:"Could not run report");}}
  async function download(){if(!run||!api.raw)return setError("Authenticated export is unavailable");try{const response=await api.raw(`/api/v1/report-runs/${run.uuid}/export.csv`);const url=URL.createObjectURL(await response.blob());const link=document.createElement("a");link.href=url;link.download=`${run.report_key}.csv`;link.click();URL.revokeObjectURL(url);}catch(reason){setError(reason instanceof Error?reason.message:"Could not export report");}}
  const categories=[...new Set(catalog.map(item=>item.category))];
  return <section className="report-workspace"><section className="card report-catalog"><h2>Report catalog <span>{catalog.length}</span></h2>{categories.map(category=><div key={category}><h3>{category}</h3>{catalog.filter(item=>item.category===category).map(item=><button key={item.key} className={selected?.key===item.key?"report-item selected":"report-item"} onClick={()=>{setSelected(item);setRun(null);setError("");}}><span>{item.title}</span><small>{item.migrated?"Available":"Migration pending"}</small></button>)}</div>)}</section><section className="card report-viewer">{selected?<><p className="eyebrow">{selected.category}</p><h2>{selected.title}</h2><small>{selected.legacy_path}</small>{selected.migrated?<form className="report-filters" onSubmit={execute}><label>From<input name="date_from" type="date"/></label><label>To<input name="date_to" type="date"/></label><label>Status<input name="status"/></label><label>Warehouse<input name="warehouse_code"/></label>{selected.key==="chart_location_activity"&&<label>Patient UUID<input name="patient_uuid" required/></label>}<button>Run report</button></form>:<p className="pending-notice">This legacy report is inventoried and remains in the migration queue.</p>}{error&&<p className="error">{error}</p>}{run&&<><div className="report-meta"><strong>{run.row_count} rows</strong><span>Checksum {run.checksum.slice(0,12)}…</span><button onClick={()=>void download()}>Export CSV</button></div><div className="report-table"><table><thead><tr>{run.columns.map(column=><th key={column}>{column.replaceAll("_"," ")}</th>)}</tr></thead><tbody>{run.rows.map((row,index)=><tr key={index}>{run.columns.map(column=><td key={column}>{String(row[column]??"—")}</td>)}</tr>)}</tbody></table></div><div className="report-totals">{Object.entries(run.totals).map(([key,value])=><span key={key}><strong>{String(value)}</strong> {key.replaceAll("_"," ")}</span>)}</div></>}</>:<div className="empty">Select a report to inspect its migration status and parameters.</div>}</section></section>;
}
