// @vitest-environment jsdom
import { cleanup,fireEvent,render,screen,waitFor } from "@testing-library/react";
import { afterEach,describe,expect,it,vi } from "vitest";
import { ReportWorkspace } from "./ReportWorkspace";

describe("ReportWorkspace",()=>{
  afterEach(cleanup);
  it("shows catalog status and renders a reproducible report run",async()=>{
    const api=vi.fn().mockResolvedValueOnce([{key:"appointments_report",title:"Appointments Report",category:"operations",permission:"patients:appt:read",legacy_path:"interface/reports/appointments_report.php",migrated:true},{key:"cqm",title:"Cqm",category:"clinical",permission:"patients:med:read",legacy_path:"interface/reports/cqm.php",migrated:false}]).mockResolvedValueOnce({uuid:"r1",report_key:"appointments_report",parameters:{},columns:["patient","status"],rows:[{patient:"Fixture, Report",status:"scheduled"}],totals:{appointments:1},row_count:1,checksum:"abcdef0123456789",created_at:"2026-01-01T00:00:00Z"});
    Object.assign(api,{raw:vi.fn()});
    render(<ReportWorkspace api={api}/>);fireEvent.click(await screen.findByText("Appointments Report"));fireEvent.click(screen.getByText("Run report"));
    expect(await screen.findByText("Fixture, Report")).toBeTruthy();expect(screen.getByText("1 rows")).toBeTruthy();expect(screen.getByText(/Checksum abcdef012345/)).toBeTruthy();
    await waitFor(()=>expect(api).toHaveBeenCalledWith("/api/v1/reports/appointments_report/runs",expect.objectContaining({method:"POST"})));
  });
  it("exposes and submits the clinical cohort dimensions",async()=>{
    const api=vi.fn().mockResolvedValueOnce([{key:"clinical_reports",title:"Clinical Reports",category:"clinical",permission:"patients:med:read",legacy_path:"interface/reports/clinical_reports.php",migrated:true}]).mockResolvedValueOnce({uuid:"r2",report_key:"clinical_reports",parameters:{},columns:["patient_name","drug"],rows:[{patient_name:"Clinical Cohort",drug:"Sumatriptan"}],totals:{patients:1},row_count:1,checksum:"abcdef0123456789",created_at:"2026-01-01T00:00:00Z"});
    render(<ReportWorkspace api={api as any}/>);fireEvent.click(await screen.findByText("Clinical Reports"));fireEvent.change(screen.getByLabelText("Drug"),{target:{value:"Suma%"}});fireEvent.click(screen.getByLabelText("Prescriptions"));fireEvent.change(screen.getByLabelText("Report option"),{target:{value:"Procedure"}});fireEvent.click(screen.getByText("Run report"));await screen.findByText("Clinical Cohort");
    const request=JSON.parse(String((api.mock.calls[1][1] as RequestInit).body));expect(request.drug_name).toBe("Suma%");expect(request.include_prescriptions).toBe(true);expect(request.clinical_type).toBe("Procedure");
  });
  it("submits appointment reconciliation scope and summary mode",async()=>{
    const api=vi.fn().mockResolvedValueOnce([{key:"appt_encounter_report",title:"Appointments and Encounters",category:"financial",permission:"acct:rep_a:read",legacy_path:"interface/reports/appt_encounter_report.php",migrated:true}]).mockResolvedValueOnce({uuid:"r3",report_key:"appt_encounter_report",parameters:{},columns:["provider","encounters"],rows:[{provider:"Doctor One",encounters:2}],totals:{encounters:2},row_count:1,checksum:"abcdef0123456789",created_at:"2026-01-01T00:00:00Z"});
    render(<ReportWorkspace api={api as any}/>);fireEvent.click(await screen.findByText("Appointments and Encounters"));fireEvent.change(screen.getByLabelText("Facility UUID"),{target:{value:"00000000-0000-0000-0000-000000000701"}});fireEvent.click(screen.getByLabelText("Provider totals only"));fireEvent.click(screen.getByText("Run report"));await screen.findByText("Doctor One");
    const request=JSON.parse(String((api.mock.calls[1][1] as RequestInit).body));expect(request.facility_uuid).toBe("00000000-0000-0000-0000-000000000701");expect(request.include_details).toBe(false);
  });
  it("submits collections responsibility and aging controls",async()=>{
    const api=vi.fn().mockResolvedValueOnce([{key:"collections_report",title:"Collections Report",category:"financial",permission:"acct:rep_a:read",legacy_path:"interface/reports/collections_report.php",migrated:true}]).mockResolvedValueOnce({uuid:"r4",report_key:"collections_report",parameters:{},columns:["insurance","balance"],rows:[{insurance:"Example Health",balance:"75.00"}],totals:{balance:"75.00"},row_count:1,checksum:"abcdef0123456789",created_at:"2026-01-01T00:00:00Z"});
    render(<ReportWorkspace api={api as any}/>);fireEvent.click(await screen.findByText("Collections Report"));fireEvent.change(screen.getByLabelText("Category"),{target:{value:"Due Ins"}});fireEvent.change(screen.getByLabelText("Age by"),{target:{value:"last_activity"}});fireEvent.change(screen.getByLabelText("Days per column"),{target:{value:"45"}});fireEvent.click(screen.getByLabelText("Positive debt only"));fireEvent.click(screen.getByText("Run report"));await screen.findByText("Example Health");
    const request=JSON.parse(String((api.mock.calls[1][1] as RequestInit).body));expect(request.collection_category).toBe("Due Ins");expect(request.age_by).toBe("last_activity");expect(request.age_increment_days).toBe(45);expect(request.with_debt_only).toBe(true);
  });
  it("submits front receipt facility and provider scope",async()=>{
    const api=vi.fn().mockResolvedValueOnce([{key:"front_receipts_report",title:"Front Receipts Report",category:"financial",permission:"acct:rep_a:read",legacy_path:"interface/reports/front_receipts_report.php",migrated:true}]).mockResolvedValueOnce({uuid:"r5",report_key:"front_receipts_report",parameters:{},columns:["patient","total"],rows:[{patient:"Receipt, Front",total:"55.00"}],totals:{total:"55.00"},row_count:1,checksum:"abcdef0123456789",created_at:"2026-01-01T00:00:00Z"});
    render(<ReportWorkspace api={api as any}/>);fireEvent.click(await screen.findByText("Front Receipts Report"));fireEvent.change(screen.getByLabelText("Facility UUID"),{target:{value:"00000000-0000-0000-0000-000000000821"}});fireEvent.change(screen.getByLabelText("Provider legacy ID"),{target:{value:"824"}});fireEvent.click(screen.getByText("Run report"));await screen.findByText("Receipt, Front");
    const request=JSON.parse(String((api.mock.calls[1][1] as RequestInit).body));expect(request.facility_uuid).toContain("821");expect(request.provider_legacy_id).toBe(824);
  });
  it("submits receipt grouping, date basis and procedure filters",async()=>{
    const api=vi.fn().mockResolvedValueOnce([{key:"receipts_by_method_report",title:"Receipts By Method Report",category:"financial",permission:"acct:rep_a:read",legacy_path:"interface/reports/receipts_by_method_report.php",migrated:true}]).mockResolvedValueOnce({uuid:"r6",report_key:"receipts_by_method_report",parameters:{},columns:["method","payments"],rows:[{method:"Credit Card",payments:"50.00"}],totals:{payments:"50.00"},row_count:1,checksum:"abcdef0123456789",created_at:"2026-01-01T00:00:00Z"});
    render(<ReportWorkspace api={api as any}/>);fireEvent.click(await screen.findByText("Receipts By Method Report"));fireEvent.change(screen.getByLabelText("Report by"),{target:{value:"check_number"}});fireEvent.change(screen.getByLabelText("Procedure code"),{target:{value:"CPT4:99213"}});fireEvent.click(screen.getByLabelText("Use invoice date"));fireEvent.click(screen.getByLabelText("Summary only"));fireEvent.click(screen.getByText("Run report"));await screen.findByText("Credit Card");
    const request=JSON.parse(String((api.mock.calls[1][1] as RequestInit).body));expect(request.receipt_report_by).toBe("check_number");expect(request.procedure_code).toBe("CPT4:99213");expect(request.use_invoice_date).toBe(true);expect(request.include_details).toBe(false);
  });
  it("submits payment gateway audit filters",async()=>{
    const api=vi.fn().mockResolvedValueOnce([{key:"payment_processing_report",title:"Payment Processing Report",category:"financial",permission:"acct:rep_a:read",legacy_path:"interface/reports/payment_processing_report.php",migrated:true}]).mockResolvedValueOnce({uuid:"r7",report_key:"payment_processing_report",parameters:{},columns:["transaction_id","action"],rows:[{transaction_id:"TRANS-1",action:"Sale"}],totals:{transactions:1},row_count:1,checksum:"abcdef0123456789",created_at:"2026-01-01T00:00:00Z"});
    render(<ReportWorkspace api={api as any}/>);fireEvent.click(await screen.findByText("Payment Processing Report"));fireEvent.change(screen.getByLabelText("Service"),{target:{value:"sphere"}});fireEvent.change(screen.getByLabelText("Transaction ID"),{target:{value:"TRANS-1"}});fireEvent.change(screen.getByLabelText("Action"),{target:{value:"Sale"}});fireEvent.click(screen.getByText("Run report"));await screen.findByText("TRANS-1");
    const request=JSON.parse(String((api.mock.calls[1][1] as RequestInit).body));expect(request.payment_service).toBe("sphere");expect(request.payment_transaction_id).toBe("TRANS-1");expect(request.payment_action).toBe("Sale");
  });
  it("submits prepayment patient and parked-credit filters",async()=>{
    const api=vi.fn().mockResolvedValueOnce([{key:"prepayment_balance_report",title:"Prepayment Balance Report",category:"financial",permission:"acct:rep_a:read",legacy_path:"interface/reports/prepayment_balance_report.php",migrated:true}]).mockResolvedValueOnce({uuid:"r8",report_key:"prepayment_balance_report",parameters:{},columns:["reference","unapplied"],rows:[{reference:"PRE-1",unapplied:"70.00"}],totals:{unapplied:"70.00"},row_count:1,checksum:"abcdef0123456789",created_at:"2026-01-01T00:00:00Z"});
    render(<ReportWorkspace api={api as any}/>);fireEvent.click(await screen.findByText("Prepayment Balance Report"));fireEvent.change(screen.getByLabelText("Patient UUID"),{target:{value:"00000000-0000-0000-0000-000000000951"}});fireEvent.click(screen.getByLabelText("Parked in global only"));fireEvent.click(screen.getByText("Run report"));await screen.findByText("PRE-1");
    const request=JSON.parse(String((api.mock.calls[1][1] as RequestInit).body));expect(request.patient_uuid).toContain("951");expect(request.parked_only).toBe(true);
  });
  it("submits service-code financial scope and important-code filter",async()=>{
    const api=vi.fn().mockResolvedValueOnce([{key:"svc_code_financial_report",title:"Svc Code Financial Report",category:"financial",permission:"acct:rep_a:read",legacy_path:"interface/reports/svc_code_financial_report.php",migrated:true}]).mockResolvedValueOnce({uuid:"r9",report_key:"svc_code_financial_report",parameters:{},columns:["procedure_code","balance_amount"],rows:[{procedure_code:"99213",balance_amount:"30.00"}],totals:{balance_amount:"30.00"},row_count:1,checksum:"abcdef0123456789",created_at:"2026-01-01T00:00:00Z"});
    render(<ReportWorkspace api={api as any}/>);fireEvent.click(await screen.findByText("Svc Code Financial Report"));fireEvent.change(screen.getByLabelText("Provider legacy ID"),{target:{value:"968"}});fireEvent.click(screen.getByLabelText("Important codes only"));fireEvent.click(screen.getByText("Run report"));await screen.findByText("99213");
    const request=JSON.parse(String((api.mock.calls[1][1] as RequestInit).body));expect(request.provider_legacy_id).toBe(968);expect(request.financial_reporting_only).toBe(true);
  });
  it("explains and runs the fixed 2026 regulatory period",async()=>{
    const api=vi.fn().mockResolvedValueOnce([{key:"rwt_2026_report",title:"Rwt 2026 Report",category:"clinical",permission:"admin:super:read",legacy_path:"interface/reports/rwt_2026_report.php",migrated:true}]).mockResolvedValueOnce({uuid:"r10",report_key:"rwt_2026_report",parameters:{},columns:["metric","measure","count"],rows:[{metric:1,measure:"generated_ccda_documents",count:2}],totals:{metrics:6},row_count:1,checksum:"abcdef0123456789",created_at:"2026-01-01T00:00:00Z"});
    render(<ReportWorkspace api={api as any}/>);fireEvent.click(await screen.findByText("Rwt 2026 Report"));expect(screen.getByText(/Fixed ONC measurement period/)).toBeTruthy();fireEvent.click(screen.getByText("Run report"));await screen.findByText("generated_ccda_documents");expect(api.mock.calls[1][0]).toContain("rwt_2026_report");
  });
  it("runs and prints a patient Superbill",async()=>{
    const print=vi.spyOn(window,"print").mockImplementation(()=>undefined);
    const api=vi.fn().mockResolvedValueOnce([{key:"custom_report_range",title:"Custom Report Range",category:"clinical",permission:"encounters:coding_a:read",legacy_path:"interface/reports/custom_report_range.php",migrated:true}]).mockResolvedValueOnce({uuid:"run-superbill",report_key:"custom_report_range",parameters:{},columns:["patient_fname","code","fee"],rows:[{patient_fname:"Ada",code:"99213",fee:"125.00"}],totals:{superbills:1},row_count:1,checksum:"a".repeat(64),created_at:"2038-04-15"});
    render(<ReportWorkspace api={api as any}/>);fireEvent.click(await screen.findByText("Custom Report Range"));fireEvent.change(screen.getByLabelText("From"),{target:{value:"2038-04-15"}});fireEvent.change(screen.getByLabelText("To"),{target:{value:"2038-04-15"}});fireEvent.change(screen.getByLabelText("Patient UUID"),{target:{value:"00000000-0000-0000-0000-000000008101"}});fireEvent.click(screen.getByText("Run report"));await screen.findByText("Ada");fireEvent.click(screen.getByText("Print Superbill"));expect(print).toHaveBeenCalled();expect(String(api.mock.calls[1][1].body)).toContain('"patient_uuid":"00000000-0000-0000-0000-000000008101"');print.mockRestore();
  });
  it("submits syndromic surveillance scope and reportable codes",async()=>{
    const api=vi.fn().mockResolvedValueOnce([{key:"non_reported",title:"Non Reported",category:"clinical",permission:"patients:med:read",legacy_path:"interface/reports/non_reported.php",migrated:true}]).mockResolvedValueOnce({uuid:"syndromic-run",report_key:"non_reported",parameters:{},columns:["issue_title","diagnosis"],rows:[{issue_title:"Influenza syndrome",diagnosis:"ICD9:487.1"}],totals:{unreported_issues:1},row_count:1,checksum:"b".repeat(64),created_at:"2039-06-05"});
    Object.assign(api,{raw:vi.fn()});render(<ReportWorkspace api={api as any}/>);fireEvent.click(await screen.findByText("Non Reported"));fireEvent.change(screen.getByLabelText("Sending facility UUID"),{target:{value:"00000000-0000-0000-0000-000000009101"}});fireEvent.change(screen.getByLabelText("Legacy reportable code IDs"),{target:{value:"101, 102"}});fireEvent.click(screen.getByText("Run report"));await screen.findByText("Influenza syndrome");expect(screen.getByText("Export and mark HL7 sent")).toBeTruthy();const request=JSON.parse(String(api.mock.calls[1][1].body));expect(request.reportable_code_ids).toEqual([101,102]);
  });
  it("submits patient ledger identity and accounting scope",async()=>{
    const api=vi.fn().mockResolvedValueOnce([{key:"pat_ledger",title:"Pat Ledger",category:"financial",permission:"acct:rep:read",legacy_path:"interface/reports/pat_ledger.php",migrated:true}]).mockResolvedValueOnce({uuid:"ledger-run",report_key:"pat_ledger",parameters:{},columns:["line_type","charge","payment"],rows:[{line_type:"unapplied_credit",charge:null,payment:"100.00"}],totals:{balance:"10.00"},row_count:1,checksum:"c".repeat(64),created_at:"2040-03-04"});
    render(<ReportWorkspace api={api as any}/>);fireEvent.click(await screen.findByText("Pat Ledger"));fireEvent.change(screen.getByLabelText("Patient UUID"),{target:{value:"00000000-0000-0000-0000-000000004201"}});fireEvent.change(screen.getByLabelText("Provider legacy ID"),{target:{value:"7"}});fireEvent.click(screen.getByText("Run report"));await screen.findByText("unapplied_credit");const request=JSON.parse(String(api.mock.calls[1][1].body));expect(request.patient_uuid).toContain("4201");expect(request.provider_legacy_id).toBe(7);
  });
  it("submits patient-list mode-specific cohort filters",async()=>{
    const api=vi.fn().mockResolvedValueOnce([{key:"patient_list_creation",title:"Patient List Creation",category:"clinical",permission:"patients:med:read",legacy_path:"interface/reports/patient_list_creation.php",migrated:true}]).mockResolvedValueOnce({uuid:"cohort-run",report_key:"patient_list_creation",parameters:{},columns:["patient_name","obs_code"],rows:[{patient_name:"Builder, Cohort",obs_code:"8302-2"}],totals:{patients:1},row_count:1,checksum:"d".repeat(64),created_at:"2026-09-15"});
    render(<ReportWorkspace api={api as any}/>);fireEvent.click(await screen.findByText("Patient List Creation"));fireEvent.change(screen.getByLabelText("Option"),{target:{value:"observs"}});fireEvent.change(screen.getByLabelText("Observation code/description"),{target:{value:"8302%"}});fireEvent.change(screen.getByLabelText("Sort order"),{target:{value:"desc"}});fireEvent.click(screen.getByText("Run report"));await screen.findByText("Builder, Cohort");const request=JSON.parse(String(api.mock.calls[1][1].body));expect(request.patient_list_option).toBe("observs");expect(request.observation_description).toBe("8302%");expect(request.patient_list_sort_order).toBe("desc");
  });
  it("submits CYP facility and summary controls",async()=>{
    const api=vi.fn().mockResolvedValueOnce([{key:"ippf_cyp_report",title:"Ippf Cyp Report",category:"clinical",permission:"acct:rep:read",legacy_path:"interface/reports/ippf_cyp_report.php",migrated:true}]).mockResolvedValueOnce({uuid:"cyp-run",report_key:"ippf_cyp_report",parameters:{},columns:["item","result"],rows:[{item:"Contraceptive service",result:"5.00"}],totals:{cyp_result:"5.00"},row_count:1,checksum:"e".repeat(64),created_at:"2026-09-15"});
    render(<ReportWorkspace api={api as any}/>);fireEvent.click(await screen.findByText("Ippf Cyp Report"));fireEvent.change(screen.getByLabelText("Facility UUID"),{target:{value:"00000000-0000-0000-0000-000000006101"}});fireEvent.click(screen.getByLabelText("Product totals only"));fireEvent.click(screen.getByText("Run report"));await screen.findByText("Contraceptive service");const request=JSON.parse(String(api.mock.calls[1][1].body));expect(request.facility_uuid).toContain("6101");expect(request.include_details).toBe(false);
  });
  it("runs the IPPF daily record with its single-day facility scope",async()=>{
    const api=vi.fn().mockResolvedValueOnce([{key:"ippf_daily",title:"Ippf Daily",category:"clinical",permission:"acct:rep:read",legacy_path:"interface/reports/ippf_daily.php",migrated:true}]).mockResolvedValueOnce({uuid:"daily-run",report_key:"ippf_daily",parameters:{},columns:["method","total_clients"],rows:[{method:"Injectable",total_clients:1}],totals:{total_clients:1},row_count:1,checksum:"f".repeat(64),created_at:"2026-09-15"});
    render(<ReportWorkspace api={api as any}/>);fireEvent.click(await screen.findByText("Ippf Daily"));expect(screen.getByText(/uses the From date/)).toBeTruthy();fireEvent.change(screen.getByLabelText("From"),{target:{value:"2026-09-15"}});fireEvent.change(screen.getByLabelText("Facility UUID"),{target:{value:"00000000-0000-0000-0000-000000006102"}});fireEvent.click(screen.getByText("Run report"));await screen.findByText("Injectable");const request=JSON.parse(String(api.mock.calls[1][1].body));expect(request.date_from).toBe("2026-09-15");expect(request.facility_uuid).toContain("6102");
  });
  it("submits multidimensional IPPF statistics controls",async()=>{
    const api=vi.fn().mockResolvedValueOnce([{key:"ippf_statistics",title:"Ippf Statistics",category:"clinical",permission:"acct:rep:read",legacy_path:"interface/reports/ippf_statistics.php",migrated:true}]).mockResolvedValueOnce({uuid:"stats-run",report_key:"ippf_statistics",parameters:{},columns:["group","total"],rows:[{group:"Injectables",total:2}],totals:{total:2},row_count:1,checksum:"1".repeat(64),created_at:"2026-09-15"});
    render(<ReportWorkspace api={api as any}/>);fireEvent.click(await screen.findByText("Ippf Statistics"));fireEvent.change(screen.getByLabelText("Report family"),{target:{value:"g"}});fireEvent.change(screen.getByLabelText("Legacy row mode"),{target:{value:"13"}});fireEvent.change(screen.getByLabelText("Content"),{target:{value:"2"}});fireEvent.click(screen.getByText("Run report"));await screen.findByText("Injectables");const request=JSON.parse(String(api.mock.calls[1][1].body));expect(request.ippf_report_type).toBe("g");expect(request.ippf_group_by).toBe("13");expect(request.ippf_content).toBe("2");expect(request.ippf_sex).toBe("all");expect(request.ippf_columns).toEqual(["total"]);
  });
  it("runs and completes AMC tracking evidence",async()=>{
    const api=vi.fn().mockResolvedValueOnce([{key:"amc_tracking",title:"Amc Tracking",category:"clinical",permission:"patients:med:read",legacy_path:"interface/reports/amc_tracking.php",migrated:true}]).mockResolvedValueOnce({uuid:"amc-run",report_key:"amc_tracking",parameters:{amc_rule:"send_sum_amc"},columns:["patient_name","source_uuid"],rows:[{patient_name:"Fixture, AMC",source_uuid:"referral-uuid"}],totals:{candidates:1},row_count:1,checksum:"2".repeat(64),created_at:"2026-09-15"}).mockResolvedValueOnce({uuid:"event",rule_id:"send_sum_amc",completed_at:"2026-09-15",electronically:true});
    render(<ReportWorkspace api={api as any}/>);fireEvent.click(await screen.findByText("Amc Tracking"));fireEvent.change(screen.getByLabelText("Rule"),{target:{value:"send_sum_amc"}});fireEvent.click(screen.getByText("Run report"));await screen.findByText("Fixture, AMC");fireEvent.click(screen.getByText("Mark electronic"));await waitFor(()=>expect(api).toHaveBeenCalledTimes(3));expect(api.mock.calls[2][0]).toContain("/amc-tracking/send_sum_amc/referral-uuid");expect(JSON.parse(String(api.mock.calls[2][1].body))).toEqual({completed:true,electronically:true});
  });
});
