// @vitest-environment jsdom
import { cleanup,fireEvent,render,screen,waitFor } from "@testing-library/react";
import { afterEach,describe,expect,it,vi } from "vitest";
import { ReportWorkspace } from "./ReportWorkspace";

describe("ReportWorkspace",()=>{
  afterEach(cleanup);
  it("shows catalog status and renders a reproducible report run",async()=>{
    const api=vi.fn().mockResolvedValueOnce([{key:"appointments_report",title:"Appointments Report",category:"operations",permission:"patients:appt:read",legacy_path:"interface/reports/appointments_report.php",migrated:true},{key:"cqm",title:"Cqm",category:"clinical",permission:"patients:med:read",legacy_path:"interface/reports/cqm.php",migrated:false}]).mockResolvedValueOnce({uuid:"r1",report_key:"appointments_report",parameters:{},columns:["patient","status"],rows:[{patient:"Fixture, Report",status:"scheduled"}],totals:{appointments:1},row_count:1,checksum:"abcdef0123456789",created_at:"2026-01-01T00:00:00Z"});
    Object.assign(api,{raw:vi.fn()});
    render(<ReportWorkspace api={api}/>);fireEvent.click(await screen.findByText("Appointments Report"));fireEvent.click(screen.getByText("Run report"));
    expect(await screen.findByText("Fixture, Report")).toBeTruthy();expect(screen.getByText("1 rows")).toBeTruthy();expect(screen.getByText(/Checksum abcdef012345/)).toBeTruthy();
    await waitFor(()=>expect(api).toHaveBeenCalledWith("/api/v1/reports/appointments_report/runs",expect.objectContaining({method:"POST"})));
  });
  it("exposes and submits the clinical cohort dimensions",async()=>{
    const api=vi.fn().mockResolvedValueOnce([{key:"clinical_reports",title:"Clinical Reports",category:"clinical",permission:"patients:med:read",legacy_path:"interface/reports/clinical_reports.php",migrated:true}]).mockResolvedValueOnce({uuid:"r2",report_key:"clinical_reports",parameters:{},columns:["patient_name","drug"],rows:[{patient_name:"Clinical Cohort",drug:"Sumatriptan"}],totals:{patients:1},row_count:1,checksum:"abcdef0123456789",created_at:"2026-01-01T00:00:00Z"});
    render(<ReportWorkspace api={api as any}/>);fireEvent.click(await screen.findByText("Clinical Reports"));fireEvent.change(screen.getByLabelText("Drug"),{target:{value:"Suma%"}});fireEvent.click(screen.getByLabelText("Prescriptions"));fireEvent.change(screen.getByLabelText("Report option"),{target:{value:"Procedure"}});fireEvent.click(screen.getByText("Run report"));await screen.findByText("Clinical Cohort");
    const request=JSON.parse(String((api.mock.calls[1][1] as RequestInit).body));expect(request.drug_name).toBe("Suma%");expect(request.include_prescriptions).toBe(true);expect(request.clinical_type).toBe("Procedure");
  });
  it("submits appointment reconciliation scope and summary mode",async()=>{
    const api=vi.fn().mockResolvedValueOnce([{key:"appt_encounter_report",title:"Appointments and Encounters",category:"financial",permission:"acct:rep_a:read",legacy_path:"interface/reports/appt_encounter_report.php",migrated:true}]).mockResolvedValueOnce({uuid:"r3",report_key:"appt_encounter_report",parameters:{},columns:["provider","encounters"],rows:[{provider:"Doctor One",encounters:2}],totals:{encounters:2},row_count:1,checksum:"abcdef0123456789",created_at:"2026-01-01T00:00:00Z"});
    render(<ReportWorkspace api={api as any}/>);fireEvent.click(await screen.findByText("Appointments and Encounters"));fireEvent.change(screen.getByLabelText("Facility UUID"),{target:{value:"00000000-0000-0000-0000-000000000701"}});fireEvent.click(screen.getByLabelText("Provider totals only"));fireEvent.click(screen.getByText("Run report"));await screen.findByText("Doctor One");
    const request=JSON.parse(String((api.mock.calls[1][1] as RequestInit).body));expect(request.facility_uuid).toBe("00000000-0000-0000-0000-000000000701");expect(request.include_details).toBe(false);
  });
  it("submits collections responsibility and aging controls",async()=>{
    const api=vi.fn().mockResolvedValueOnce([{key:"collections_report",title:"Collections Report",category:"financial",permission:"acct:rep_a:read",legacy_path:"interface/reports/collections_report.php",migrated:true}]).mockResolvedValueOnce({uuid:"r4",report_key:"collections_report",parameters:{},columns:["insurance","balance"],rows:[{insurance:"Example Health",balance:"75.00"}],totals:{balance:"75.00"},row_count:1,checksum:"abcdef0123456789",created_at:"2026-01-01T00:00:00Z"});
    render(<ReportWorkspace api={api as any}/>);fireEvent.click(await screen.findByText("Collections Report"));fireEvent.change(screen.getByLabelText("Category"),{target:{value:"Due Ins"}});fireEvent.change(screen.getByLabelText("Age by"),{target:{value:"last_activity"}});fireEvent.change(screen.getByLabelText("Days per column"),{target:{value:"45"}});fireEvent.click(screen.getByLabelText("Positive debt only"));fireEvent.click(screen.getByText("Run report"));await screen.findByText("Example Health");
    const request=JSON.parse(String((api.mock.calls[1][1] as RequestInit).body));expect(request.collection_category).toBe("Due Ins");expect(request.age_by).toBe("last_activity");expect(request.age_increment_days).toBe(45);expect(request.with_debt_only).toBe(true);
  });
  it("submits front receipt facility and provider scope",async()=>{
    const api=vi.fn().mockResolvedValueOnce([{key:"front_receipts_report",title:"Front Receipts Report",category:"financial",permission:"acct:rep_a:read",legacy_path:"interface/reports/front_receipts_report.php",migrated:true}]).mockResolvedValueOnce({uuid:"r5",report_key:"front_receipts_report",parameters:{},columns:["patient","total"],rows:[{patient:"Receipt, Front",total:"55.00"}],totals:{total:"55.00"},row_count:1,checksum:"abcdef0123456789",created_at:"2026-01-01T00:00:00Z"});
    render(<ReportWorkspace api={api as any}/>);fireEvent.click(await screen.findByText("Front Receipts Report"));fireEvent.change(screen.getByLabelText("Facility UUID"),{target:{value:"00000000-0000-0000-0000-000000000821"}});fireEvent.change(screen.getByLabelText("Provider legacy ID"),{target:{value:"824"}});fireEvent.click(screen.getByText("Run report"));await screen.findByText("Receipt, Front");
    const request=JSON.parse(String((api.mock.calls[1][1] as RequestInit).body));expect(request.facility_uuid).toContain("821");expect(request.provider_legacy_id).toBe(824);
  });
  it("submits receipt grouping, date basis and procedure filters",async()=>{
    const api=vi.fn().mockResolvedValueOnce([{key:"receipts_by_method_report",title:"Receipts By Method Report",category:"financial",permission:"acct:rep_a:read",legacy_path:"interface/reports/receipts_by_method_report.php",migrated:true}]).mockResolvedValueOnce({uuid:"r6",report_key:"receipts_by_method_report",parameters:{},columns:["method","payments"],rows:[{method:"Credit Card",payments:"50.00"}],totals:{payments:"50.00"},row_count:1,checksum:"abcdef0123456789",created_at:"2026-01-01T00:00:00Z"});
    render(<ReportWorkspace api={api as any}/>);fireEvent.click(await screen.findByText("Receipts By Method Report"));fireEvent.change(screen.getByLabelText("Report by"),{target:{value:"check_number"}});fireEvent.change(screen.getByLabelText("Procedure code"),{target:{value:"CPT4:99213"}});fireEvent.click(screen.getByLabelText("Use invoice date"));fireEvent.click(screen.getByLabelText("Summary only"));fireEvent.click(screen.getByText("Run report"));await screen.findByText("Credit Card");
    const request=JSON.parse(String((api.mock.calls[1][1] as RequestInit).body));expect(request.receipt_report_by).toBe("check_number");expect(request.procedure_code).toBe("CPT4:99213");expect(request.use_invoice_date).toBe(true);expect(request.include_details).toBe(false);
  });
  it("submits payment gateway audit filters",async()=>{
    const api=vi.fn().mockResolvedValueOnce([{key:"payment_processing_report",title:"Payment Processing Report",category:"financial",permission:"acct:rep_a:read",legacy_path:"interface/reports/payment_processing_report.php",migrated:true}]).mockResolvedValueOnce({uuid:"r7",report_key:"payment_processing_report",parameters:{},columns:["transaction_id","action"],rows:[{transaction_id:"TRANS-1",action:"Sale"}],totals:{transactions:1},row_count:1,checksum:"abcdef0123456789",created_at:"2026-01-01T00:00:00Z"});
    render(<ReportWorkspace api={api as any}/>);fireEvent.click(await screen.findByText("Payment Processing Report"));fireEvent.change(screen.getByLabelText("Service"),{target:{value:"sphere"}});fireEvent.change(screen.getByLabelText("Transaction ID"),{target:{value:"TRANS-1"}});fireEvent.change(screen.getByLabelText("Action"),{target:{value:"Sale"}});fireEvent.click(screen.getByText("Run report"));await screen.findByText("TRANS-1");
    const request=JSON.parse(String((api.mock.calls[1][1] as RequestInit).body));expect(request.payment_service).toBe("sphere");expect(request.payment_transaction_id).toBe("TRANS-1");expect(request.payment_action).toBe("Sale");
  });
  it("submits prepayment patient and parked-credit filters",async()=>{
    const api=vi.fn().mockResolvedValueOnce([{key:"prepayment_balance_report",title:"Prepayment Balance Report",category:"financial",permission:"acct:rep_a:read",legacy_path:"interface/reports/prepayment_balance_report.php",migrated:true}]).mockResolvedValueOnce({uuid:"r8",report_key:"prepayment_balance_report",parameters:{},columns:["reference","unapplied"],rows:[{reference:"PRE-1",unapplied:"70.00"}],totals:{unapplied:"70.00"},row_count:1,checksum:"abcdef0123456789",created_at:"2026-01-01T00:00:00Z"});
    render(<ReportWorkspace api={api as any}/>);fireEvent.click(await screen.findByText("Prepayment Balance Report"));fireEvent.change(screen.getByLabelText("Patient UUID"),{target:{value:"00000000-0000-0000-0000-000000000951"}});fireEvent.click(screen.getByLabelText("Parked in global only"));fireEvent.click(screen.getByText("Run report"));await screen.findByText("PRE-1");
    const request=JSON.parse(String((api.mock.calls[1][1] as RequestInit).body));expect(request.patient_uuid).toContain("951");expect(request.parked_only).toBe(true);
  });
  it("submits service-code financial scope and important-code filter",async()=>{
    const api=vi.fn().mockResolvedValueOnce([{key:"svc_code_financial_report",title:"Svc Code Financial Report",category:"financial",permission:"acct:rep_a:read",legacy_path:"interface/reports/svc_code_financial_report.php",migrated:true}]).mockResolvedValueOnce({uuid:"r9",report_key:"svc_code_financial_report",parameters:{},columns:["procedure_code","balance_amount"],rows:[{procedure_code:"99213",balance_amount:"30.00"}],totals:{balance_amount:"30.00"},row_count:1,checksum:"abcdef0123456789",created_at:"2026-01-01T00:00:00Z"});
    render(<ReportWorkspace api={api as any}/>);fireEvent.click(await screen.findByText("Svc Code Financial Report"));fireEvent.change(screen.getByLabelText("Provider legacy ID"),{target:{value:"968"}});fireEvent.click(screen.getByLabelText("Important codes only"));fireEvent.click(screen.getByText("Run report"));await screen.findByText("99213");
    const request=JSON.parse(String((api.mock.calls[1][1] as RequestInit).body));expect(request.provider_legacy_id).toBe(968);expect(request.financial_reporting_only).toBe(true);
  });
  it("explains and runs the fixed 2026 regulatory period",async()=>{
    const api=vi.fn().mockResolvedValueOnce([{key:"rwt_2026_report",title:"Rwt 2026 Report",category:"clinical",permission:"admin:super:read",legacy_path:"interface/reports/rwt_2026_report.php",migrated:true}]).mockResolvedValueOnce({uuid:"r10",report_key:"rwt_2026_report",parameters:{},columns:["metric","measure","count"],rows:[{metric:1,measure:"generated_ccda_documents",count:2}],totals:{metrics:6},row_count:1,checksum:"abcdef0123456789",created_at:"2026-01-01T00:00:00Z"});
    render(<ReportWorkspace api={api as any}/>);fireEvent.click(await screen.findByText("Rwt 2026 Report"));expect(screen.getByText(/Fixed ONC measurement period/)).toBeTruthy();fireEvent.click(screen.getByText("Run report"));await screen.findByText("generated_ccda_documents");expect(api.mock.calls[1][0]).toContain("rwt_2026_report");
  });
});
